/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-05-27 01:14:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class get_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("/WEB-INF/views/board/../includes/footer.jsp", Long.valueOf(1716770234624L));
    _jspx_dependants.put("jar:file:/C:/java/Spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Trip03/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/java/Spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Trip03/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/board/../includes/header1.jsp", Long.valueOf(1716535517938L));
    _jspx_dependants.put("/WEB-INF/lib/spring-security-taglibs-5.2.7.RELEASE.jar", Long.valueOf(1714376254473L));
    _jspx_dependants.put("jar:file:/C:/java/Spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Trip03/WEB-INF/lib/spring-security-taglibs-5.2.7.RELEASE.jar!/META-INF/security.tld", Long.valueOf(1602058062000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1712112365428L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fvar_005fproperty_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fvar_005fproperty_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.release();
    _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fvar_005fproperty_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/list.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css\">\r\n");
      out.write("<script	src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("<script	src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/d41dbe5e59.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\n");
      out.write("    \n");
      out.write("        \n");
      out.write("<!DOCTYPE html>\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"utf-8\">\n");
      out.write("        <title>Flex - Responsive HTML Template</title>\n");
      out.write("    	<meta name=\"description\" content=\"\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<!-- \n");
      out.write("Flex Template \n");
      out.write("http://www.templatemo.com/tm-406-flex\n");
      out.write("-->\n");
      out.write("        <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'>\n");
      out.write("        <link rel=\"stylesheet\" href=\"/resources/css/bootstrap.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"/resources/css/font-awesome.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"/resources/css/animate.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"/resources/css/templatemo_misc.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"/resources/css/templatemo_style.css\">\n");
      out.write("\n");
      out.write("        <script src=\"/resources/js/vendor/modernizr-2.6.1-respond-1.1.0.min.js\"></script>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("      <div class=\"site-header\">\n");
      out.write("                <div class=\"main-header\">\n");
      out.write("                        <div id=\"menu-wrapper\">\n");
      out.write("                            <div class=\"row\">\n");
      out.write("                                <div class=\"logo-wrapper col-md-2 col-sm-2\">\n");
      out.write("                                    <h1>\n");
      out.write("                                        <a href=\"/main\">TRIP</a>\n");
      out.write("                                    </h1>\n");
      out.write("                                </div> <!-- /.logo-wrapper -->\n");
      out.write("                                <div class=\"col-md-10 col-sm-10 main-menu text-right\">\n");
      out.write("                                    <ul class=\"menu\">\n");
      out.write("                                        <li class=\"active\"><a href=\"/main\">메인 홈</a></li>\n");
      out.write("                                        <li><a href=\"#portfolio\">여행지</a></li>\n");
      out.write("                                        <li><a href=\"#services\">여행 계획</a></li>\n");
      out.write("                                        <li><a href=\"/board/list\">게시판</a> </li>\n");
      out.write("                                        <li><a href=\"/member/mypage\">마이페이지</a> </li>\n");
      out.write("                                        <li><a href=\"#\">고객 센터</a></li> \n");
      out.write("                                        ");
      if (_jspx_meth_sec_005fauthorize_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                                        ");
      if (_jspx_meth_sec_005fauthorize_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                                    </ul>                                    \n");
      out.write("                                </div> <!-- /.main-menu -->\n");
      out.write("                            </div> <!-- /.row -->\n");
      out.write("                        </div> <!-- /#menu-wrapper -->                        \n");
      out.write("                </div> <!-- /.main-header -->\n");
      out.write("            </div> <!-- /.site-header -->\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js\"></script>        ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div  class=\"page-title\">\r\n");
      out.write(" <h3>HEADER</h3>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("   <div class=\"page-title\">\r\n");
      out.write("        <div class=\"container\" style=\"margin-top: 150px\">\r\n");
      out.write("            <h3>B O A R D</h3>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("   \r\n");
      out.write("  <!-- board list area -->\r\n");
      out.write("    <div id=\"board-list\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("				<div class=\"form-group\">\r\n");
      out.write("					<label><strong>글쓴이</strong></label>\r\n");
      out.write("					<input class=\"form-control\"	name=\"member_email\" \r\n");
      out.write("					value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.member_email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" style=\"background-color: white; border: none;\" readonly=\"readonly\">\r\n");
      out.write("					<label><strong>제목</strong></label>\r\n");
      out.write("					<input class=\"form-control\" name=\"title\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" style=\"background-color: white; margin-bottom: 50px;  border: none;\" readonly=\"readonly\">\r\n");
      out.write("					<textarea rows=\"3\" class=\"form-control\" name=\"content\" readonly=\"readonly\" style=\"resize: none; background-color: white; width:1290px; height: 600px;\"> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("				");
      if (_jspx_meth_sec_005fauthentication_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("				");
      if (_jspx_meth_sec_005fauthorize_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("				<button data-oper='list' class=\"btn btn-dark\"  style=\"margin-top: 20px; margin-right: 20px; float: right;\">돌아가기</button>\r\n");
      out.write("				\r\n");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("				\r\n");
      out.write("				<form id=\"operForm\" action=\"/board/modify\" method=\"get\">\r\n");
      out.write("					<input type=\"hidden\" id=\"board_id\" name=\"board_id\" value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.board_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'> \r\n");
      out.write("					<input type=\"hidden\"	name=\"pageNum\" value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cri.pageNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'> \r\n");
      out.write("					<input type=\"hidden\" name=\"amount\" value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cri.amount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'> \r\n");
      out.write("					<input type=\"hidden\" name=\"type\" value=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cri.type}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("> \r\n");
      out.write("					<input type=\"hidden\" name=\"keyword\" value=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cri.keyword}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">\r\n");
      out.write("				</form>\r\n");
      out.write("				\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        	<form id=\"actionForm\" action=\"/board/list\" method=\"get\">\r\n");
      out.write("		<input type=\"hidden\" name=\"pageNum\" value=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageMaker.cri.pageNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">\r\n");
      out.write("		<input type=\"hidden\" name=\"amount\" value=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageMaker.cri.amount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">\r\n");
      out.write("		<input type=\"hidden\" name=\"type\" value=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageMaker.cri.type}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">\r\n");
      out.write("		<input type=\"hidden\" name=\"keyword\" value=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageMaker.cri.keyword}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">\r\n");
      out.write("	</form>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("<div class=\"container\" style=\"margin-top: 100px\">\r\n");
      out.write("<div class=\"card mb-2\">\r\n");
      out.write("	<div class=\"card-header bg-light\">\r\n");
      out.write("	        <img alt=\"\" src=\"/resources/image/reply.png\"><strong>REPLY</strong>\r\n");
      out.write("	        \r\n");
      out.write("	");
      if (_jspx_meth_sec_005fauthorize_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	 </div>\r\n");
      out.write("	 \r\n");
      out.write("	<div class=\"panel-body\">\r\n");
      out.write("		<ul class=\"chat\">\r\n");
      out.write("					<li class=\"left clearfix\" data-rno='12'>\r\n");
      out.write("						<div>\r\n");
      out.write("							<div class=\"header\">\r\n");
      out.write("								<strong class=\"primary-font\"></strong>\r\n");
      out.write("			<small class=\"pull-right text-muted\"></small>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<p></p>\r\n");
      out.write("					</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("			\r\n");
      out.write("				\r\n");
      out.write("		<!-- 페이징 처리 -->\r\n");
      out.write("			<div class=\"panel-footer\" style=\"float: right; margin-right: 20px;\"></div>\r\n");
      out.write("		<!-- End 페이징 처리 -->\r\n");
      out.write("			\r\n");
      out.write("			    \r\n");
      out.write("    	<!-- The Modal -->\r\n");
      out.write("	<div class=\"modal\" id=\"myModal\">\r\n");
      out.write("		<div class=\"modal-dialog\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("				<!-- Modal Header -->\r\n");
      out.write("				<div class=\"modal-header\">\r\n");
      out.write("					<h4 class=\"modal-title\">R E P L Y</h4>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<!-- Modal body -->\r\n");
      out.write("				<div class=\"modal-body\">\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("						<label>이름</label> \r\n");
      out.write("						<input class=\"form-control\"	name=\"member_email\" value=\"New member_email.......\" readonly=\"readonly\">\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("						<label>댓글내용</label> \r\n");
      out.write("						<input class=\"form-control\" name=\"reply\" value=\"New Reply.......\">\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("						<label>댓글작성일자</label> \r\n");
      out.write("						<input class=\"form-control\" name=\"replyDate\" value=\"\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- Modal footer -->\r\n");
      out.write("				<div class=\"modal-footer\">\r\n");
      out.write("					<button id=\"modalRegisterBtn\" type=\"button\" class=\"btn btn-primary\">등록</button>\r\n");
      out.write("					<button id=\"modalModBtn\" type=\"button\" class=\"btn btn-warning\">수정</button>\r\n");
      out.write("					<button id=\"modalRemoveBtn\" type=\"button\" class=\"btn btn-danger\">삭제</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- End The Modal -->\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<script type=\"text/javascript\" src=\"/resources/js/reply.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\" src=\"/resources/js/like.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("	\r\n");
      out.write("	console.log(\"JS TEST................\")\r\n");
      out.write("	\r\n");
      out.write("	var bnoValue = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.board_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("	var replyUL = $(\".chat\")\r\n");
      out.write("	\r\n");
      out.write("	showList(1);\r\n");
      out.write("	\r\n");
      out.write("	function showList(page) {\r\n");
      out.write("	    replyService.getList({ board_id: bnoValue, page: page }, function(replyCnt, list) {\r\n");
      out.write("	        // 마지막 페이지 처리\r\n");
      out.write("	        if (page === -1) {\r\n");
      out.write("	            var pageNum = Math.ceil(replyCnt / 10.0);\r\n");
      out.write("	            // 마지막 페이지에서는 재귀 호출을 하지 않도록 수정\r\n");
      out.write("	            if (pageNum !== page) {\r\n");
      out.write("	                showList(pageNum);\r\n");
      out.write("	            }\r\n");
      out.write("	            return;\r\n");
      out.write("	        }\r\n");
      out.write("\r\n");
      out.write("	        var str = \"\";\r\n");
      out.write("\r\n");
      out.write("	        if (list == null || list.length === 0) {\r\n");
      out.write("	            replyUL.html(\"\");\r\n");
      out.write("	            return;\r\n");
      out.write("	        }\r\n");
      out.write("\r\n");
      out.write("	        for (var i = 0; i < list.length; i++) {\r\n");
      out.write("	            str += \"<li class='left clearfix' data-rno='\" + list[i].replyNum + \"'>\"; \r\n");
      out.write("	            str += \"<div>\";\r\n");
      out.write("	            str += \"<div class='header'>\";\r\n");
      out.write("	            str += \"<strong class='primary-font'>\" + list[i].member_email + \"</strong>\";\r\n");
      out.write("	            str += \"<small class='pull-right text-muted'> \"+ list[i].replyDate +\" </small>\"\r\n");
      out.write("	            str += \"</div>\";\r\n");
      out.write("	            str += \"</div>\";\r\n");
      out.write("	            str += \"<p>\" + list[i].reply + \"</p></li>\";\r\n");
      out.write("	        }\r\n");
      out.write("	        replyUL.html(str);\r\n");
      out.write("\r\n");
      out.write("	        showReplyPage(replyCnt);\r\n");
      out.write("	    });\r\n");
      out.write("	} // End showList\r\n");
      out.write("		\r\n");
      out.write("	var modal = $(\".modal\")\r\n");
      out.write("	var modalInputReply = modal.find(\"input[name='reply']\")\r\n");
      out.write("	var modalInputmember_email = modal.find(\"input[name='member_email']\")\r\n");
      out.write("	var modalInputReplyDate = modal.find(\"input[name='replyDate']\")\r\n");
      out.write("	\r\n");
      out.write("	var modalRegisterBtn = $(\"#modalRegisterBtn\");\r\n");
      out.write("	var modalModBtn = $(\"#modalModBtn\");\r\n");
      out.write("	var modalRemoveBtn = $(\"#modalRemoveBtn\");\r\n");
      out.write("	var modalCloseBtn = $(\"#modalCloseBtn\")\r\n");
      out.write("	\r\n");
      out.write("	var member_email = null;\r\n");
      out.write("	\r\n");
      out.write("	");
      if (_jspx_meth_sec_005fauthorize_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	$(\"#addReplyBtn\").on(\"click\", function(e){\r\n");
      out.write("		\r\n");
      out.write("		modal.find(\"input\").val(\"\")\r\n");
      out.write("		modal.find(\"input[name='member_email']\").val(member_email);\r\n");
      out.write("		modalInputReplyDate.closest(\"div\").hide();\r\n");
      out.write("		modal.find(\"button[id != 'modalCloseBtn']\").hide()\r\n");
      out.write("		modalRegisterBtn.show()\r\n");
      out.write("		\r\n");
      out.write("		$(\".modal\").modal(\"show\");\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	// 좋아요 버튼 클릭 이벤트 핸들러\r\n");
      out.write("	$(\"#likeButton\").on(\"click\", function(e){\r\n");
      out.write("	    var userEmail = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.member_email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"; // 이 부분은 실제로 유저의 이메일을 가져오는 로직으로 대체되어야 합니다.\r\n");
      out.write("	    var boardId = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.board_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"; // 게시물의 ID를 가져오는 로직으로 대체되어야 합니다.\r\n");
      out.write("\r\n");
      out.write("	    if (userEmail && boardId) {\r\n");
      out.write("	        var like = {\r\n");
      out.write("	            board_id: boardId,\r\n");
      out.write("	            member_email: userEmail\r\n");
      out.write("	        };\r\n");
      out.write("\r\n");
      out.write("	        if ($(this).hasClass(\"liked\")) {\r\n");
      out.write("	            // 좋아요 취소 요청\r\n");
      out.write("	            boardService.removelike(like, function(result){\r\n");
      out.write("	                console.log(\"좋아요 취소\");\r\n");
      out.write("	                // 좋아요 취소 후 버튼 상태 및 텍스트 변경\r\n");
      out.write("	                $(\"#likeButton\").removeClass(\"liked\").html('<img alt=\"\" src=\"/resources/image/likeboard.png\">');\r\n");
      out.write("	                // 로컬 스토리지에서 좋아요 상태 제거\r\n");
      out.write("	                localStorage.removeItem(\"liked_\" + boardId);\r\n");
      out.write("	            });\r\n");
      out.write("	        } else {\r\n");
      out.write("	            // 좋아요 등록 요청\r\n");
      out.write("	            boardService.addlike(like, function(result){\r\n");
      out.write("	                console.log(\"좋아요 등록\");\r\n");
      out.write("	                // 좋아요 등록 후 버튼 상태 및 텍스트 변경\r\n");
      out.write("	                $(\"#likeButton\").addClass(\"liked\").html('<img alt=\"\" src=\"/resources/image/unlikeboard.png\">');\r\n");
      out.write("	                // 로컬 스토리지에 좋아요 상태 저장\r\n");
      out.write("	                localStorage.setItem(\"liked_\" + boardId, true);\r\n");
      out.write("	            });\r\n");
      out.write("	        }\r\n");
      out.write("	    } else {\r\n");
      out.write("	        // 값이 주어지지 않은 경우에는 처리 필요\r\n");
      out.write("	    }\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("	// 페이지 로드 시 로컬 스토리지에서 좋아요 상태 확인하여 버튼 초기화\r\n");
      out.write("	$(document).ready(function() {\r\n");
      out.write("		\r\n");
      out.write("		var modal = $(\".modal\")\r\n");
      out.write("	    var boardId = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.board_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"; // 게시물의 ID를 가져오는 로직으로 대체되어야 합니다.\r\n");
      out.write("\r\n");
      out.write("	    if (boardId) {\r\n");
      out.write("	        // 로컬 스토리지에서 좋아요 상태 확인\r\n");
      out.write("	        var isLiked = localStorage.getItem(\"liked_\" + boardId);\r\n");
      out.write("	        if (isLiked === \"true\") {\r\n");
      out.write("	            // 좋아요 상태일 때 버튼 초기화\r\n");
      out.write("	            $(\"#likeButton\").addClass(\"liked\").html('<img alt=\"\" src=\"/resources/image/unlikeboard.png\">');\r\n");
      out.write("	        } else {\r\n");
      out.write("	            // 좋아요 상태가 아닐 때 버튼 초기화\r\n");
      out.write("	            $(\"#likeButton\").removeClass(\"liked\").html('<img alt=\"\" src=\"/resources/image/likeboard.png\">');\r\n");
      out.write("	        }\r\n");
      out.write("	    } else {\r\n");
      out.write("	        // 게시물 ID가 주어지지 않은 경우에는 처리 필요\r\n");
      out.write("	    }\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	//댓글 등록\r\n");
      out.write("	 modalRegisterBtn.on(\"click\", function(e){\r\n");
      out.write("        \r\n");
      out.write("        console.log(\"register...............\")\r\n");
      out.write("    \r\n");
      out.write("        var reply = {\r\n");
      out.write("            reply : modalInputReply.val(),\r\n");
      out.write("            member_email: member_email, // member_email 값을 사용하여 댓글의 작성자 설정\r\n");
      out.write("            board_id : bnoValue\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        replyService.add(reply, function(result){\r\n");
      out.write("            alert(result)\r\n");
      out.write("            modal.find(\"input\").val(\"\")\r\n");
      out.write("            modal.modal(\"hide\")\r\n");
      out.write("            \r\n");
      out.write("            showList(-1)\r\n");
      out.write("        })\r\n");
      out.write("        \r\n");
      out.write("    }) // End 댓글 등록\r\n");
      out.write("	\r\n");
      out.write("	//이벤트 위임을 통한 댓글 클릭 이벤트\r\n");
      out.write("	$(\".chat\").on(\"click\",\"li\", function(e){\r\n");
      out.write("		\r\n");
      out.write("		e.preventDefault(); // 이벤트 기본 동작 방지\r\n");
      out.write("		\r\n");
      out.write("		console.log(\"get...............\")\r\n");
      out.write("		\r\n");
      out.write("		var replyNum = $(this).data(\"rno\")\r\n");
      out.write("		\r\n");
      out.write("		replyService.get(replyNum, function(reply){\r\n");
      out.write("			modalInputReply.val(reply.reply)\r\n");
      out.write("			modalInputmember_email.val(reply.member_email)\r\n");
      out.write("			modalInputReplyDate.val(replyService.displayTime(reply.replyDate)).attr(\"readonly\", \"readonly\")\r\n");
      out.write("			\r\n");
      out.write("			modal.data(\"rno\", reply.replyNum)\r\n");
      out.write("			\r\n");
      out.write("			modal.find(\"button[id != 'modalCloseBtn']\").hide()\r\n");
      out.write("			modalModBtn.show()\r\n");
      out.write("			modalRemoveBtn.show()\r\n");
      out.write("			\r\n");
      out.write("			$(\".modal\").modal(\"show\")\r\n");
      out.write("			\r\n");
      out.write("		})			\r\n");
      out.write("	})  //이벤트 위임\r\n");
      out.write("	\r\n");
      out.write("	//댓글 수정\r\n");
      out.write("	modalModBtn.on(\"click\", function(e){\r\n");
      out.write("		console.log(\"update...............\")\r\n");
      out.write("		\r\n");
      out.write("		var originalmember_email = member_email;\r\n");
      out.write("		\r\n");
      out.write("		var reply = {\r\n");
      out.write("			reply: 	modalInputReply.val(),\r\n");
      out.write("			replyNum: modal.data(\"rno\"),\r\n");
      out.write("			member_email: originalmember_email\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("		if(!member_email){\r\n");
      out.write("			alert(\"로그인 후 수정이 가능합니다.\")\r\n");
      out.write("			modal.modal(\"hide\")\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if(member_email != originalmember_email){\r\n");
      out.write("			alert(originalmember_email)\r\n");
      out.write("			alert(\"본인이 작성한 댓글만 수정이 가능합니다.\")\r\n");
      out.write("			modal.modal(\"hide\");\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		replyService.update(reply, function(result){\r\n");
      out.write("			\r\n");
      out.write("			alert(result)\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("		})\r\n");
      out.write("		modal.modal(\"hide\")\r\n");
      out.write("\r\n");
      out.write("		showList(pageNum)\r\n");
      out.write("	})  //End 댓글 수정\r\n");
      out.write("\r\n");
      out.write("	//댓글 삭제\r\n");
      out.write("	modalRemoveBtn.on(\"click\", function(e){\r\n");
      out.write("		\r\n");
      out.write("		console.log(\"remove...............\")\r\n");
      out.write("		\r\n");
      out.write("		let replyNum =  modal.data(\"rno\")\r\n");
      out.write("		\r\n");
      out.write("		if(!member_email){\r\n");
      out.write("			alert(\"로그인 후 삭제가 가능합니다.\")\r\n");
      out.write("			modal.modal(\"hide\")\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		var originalmember_email = member_email;\r\n");
      out.write("		\r\n");
      out.write("		if(member_email != originalmember_email){\r\n");
      out.write("			alert(\"본인이 작성한 댓글만 삭제가 가능합니다.\")\r\n");
      out.write("			modal.modal(\"hide\")\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		replyService.remove(replyNum,originalmember_email, function(result){\r\n");
      out.write("			\r\n");
      out.write("			alert(result);\r\n");
      out.write("			\r\n");
      out.write("		})\r\n");
      out.write("		\r\n");
      out.write("		modal.modal(\"hide\")\r\n");
      out.write("			showList(pageNum)\r\n");
      out.write("	})  //End 댓글 삭제\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	var pageNum = 1\r\n");
      out.write("	var replyPageFooter = $(\".panel-footer\")\r\n");
      out.write("	\r\n");
      out.write("	function showReplyPage(replyCnt){\r\n");
      out.write("		\r\n");
      out.write("		var endNum = Math.ceil(pageNum / 10.0) * 10\r\n");
      out.write("		var startNum = endNum - 9\r\n");
      out.write("		\r\n");
      out.write("		var prev = startNum != 1\r\n");
      out.write("		var next = false;\r\n");
      out.write("		\r\n");
      out.write("		if(endNum * 10 >= replyCnt){\r\n");
      out.write("			endNum = Math.ceil(replyCnt/10.0)\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if(endNum * 10 < replyCnt){\r\n");
      out.write("			next = true\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		var str = \"<ul class='pagination pull-right'>\";\r\n");
      out.write("		\r\n");
      out.write("		if(prev){\r\n");
      out.write("			str += \"<li class='page-item'><a class='page-link' href='\"+ (startNum-1) +\"'>이전</a></li>\";\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		for(var i=startNum; i<=endNum; i++){\r\n");
      out.write("			var active  = pageNum ==i? \"active\": \"\";\r\n");
      out.write("			\r\n");
      out.write("			str += \"<li class='page-item \"+ active +\" '><a class='page-link' href='\"+i+\"'>\"+i+\"</a></li>\";\r\n");
      out.write("					\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if(next){\r\n");
      out.write("			str += \"<li class='page-item'><a class='page-link' href='\"+ (endNum+1) +\"'>다음</a></li>\";\r\n");
      out.write("		}\r\n");
      out.write("		str += \"</ul>\"\r\n");
      out.write("		\r\n");
      out.write("		replyPageFooter.html(str)\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	replyPageFooter.on(\"click\", \"li a\", function(e){\r\n");
      out.write("		e.preventDefault();	\r\n");
      out.write("		\r\n");
      out.write("		var targetPageNum = $(this).attr(\"href\")\r\n");
      out.write("		\r\n");
      out.write("		pageNum = targetPageNum\r\n");
      out.write("		\r\n");
      out.write("		showList(pageNum);\r\n");
      out.write("	})\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write(" 	$(document).ready(function(){\r\n");
      out.write(" 		\r\n");
      out.write(" 		let operForm = $(\"#operForm\");\r\n");
      out.write(" 		\r\n");
      out.write(" 		$(\"button[data-oper='modify']\").on(\"click\",function(e){\r\n");
      out.write(" 			operForm.submit();\r\n");
      out.write(" 		})\r\n");
      out.write("\r\n");
      out.write(" 		$(\"button[data-oper='list']\").on(\"click\",function(e){\r\n");
      out.write(" 			operForm.find(\"#board_id\").remove();\r\n");
      out.write(" 			operForm.attr(\"action\", \"/board/list\")\r\n");
      out.write(" 			operForm.submit();\r\n");
      out.write(" 		})\r\n");
      out.write(" 		\r\n");
      out.write(" 	});\r\n");
      out.write(" </script>\r\n");
      out.write(" \r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\n");
      out.write("\n");
      out.write("  </div>\n");
      out.write("        <!-- /#page-wrapper -->\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("    <!-- /#wrapper -->\n");
      out.write("\n");
      out.write("    <!-- jQuery -->\n");
      out.write("    <script src=\"/resources/vendor/jquery/jquery.min.js\"></script>\n");
      out.write("\n");
      out.write("    <!-- Bootstrap Core JavaScript -->\n");
      out.write("    <script src=\"/resources/vendor/bootstrap/js/bootstrap.min.js\"></script>\n");
      out.write("\n");
      out.write("    <!-- Metis Menu Plugin JavaScript -->\n");
      out.write("    <script src=\"/resources/vendor/metisMenu/metisMenu.min.js\"></script>\n");
      out.write("\n");
      out.write("    <!-- DataTables JavaScript -->\n");
      out.write("    <script src=\"/resources/vendor/datatables/js/jquery.dataTables.min.js\"></script>\n");
      out.write("    <script src=\"/resources/vendor/datatables-plugins/dataTables.bootstrap.min.js\"></script>\n");
      out.write("    <script src=\"/resources/vendor/datatables-responsive/dataTables.responsive.js\"></script>\n");
      out.write("    <!-- Custom Theme JavaScript -->\n");
      out.write("    <script src=\"/resources/dist/js/sb-admin-2.js\"></script>\n");
      out.write("\n");
      out.write("    <!-- Page-Level Demo Scripts - Tables - Use for reference -->\n");
      out.write("    <script>\n");
      out.write("    $(document).ready(function() {\n");
      out.write("        $('#dataTables-example').DataTable({\n");
      out.write("            responsive: true\n");
      out.write("        });\n");
      out.write("        \n");
      out.write("        $(\".sidebar-nav\")\n");
      out.write("    	.attr(\"class\", \"sidebar-nav navbar-collapse collapse\")\n");
      out.write("    	.attr(\"aria-expanded\", 'false')\n");
      out.write("    	.attr(\"sytle\", \"height:1px\")\n");
      out.write("        \n");
      out.write("    });\n");
      out.write("    </script>\n");
      out.write("    \n");
      out.write("    <footer class=\"d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top\">\n");
      out.write("    <div class=\"col-md-4 d-flex align-items-center\">\n");
      out.write("      <a href=\"/\" class=\"mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1\">\n");
      out.write("        <svg class=\"bi\" width=\"30\" height=\"24\"><use xlink:href=\"#bootstrap\"></use></svg>\n");
      out.write("      </a>\n");
      out.write("      <span class=\"mb-3 mb-md-0 text-muted\">© 2024 Tripgo? Company, Inc<br><br>\n");
      out.write("      <li style=\"line-height:60%\" class=\"footerlistyle\"><a href=\"\" style=\"text-decoration: none\" class=\"footerastyle\">이용약관</a></li><br>\n");
      out.write("      <li style=\"line-height:60%\" class=\"footerlistyle\"><a href=\"\" style=\"text-decoration: none\" class=\"footerastyle\">개인정보처리방침</a></li><br>\n");
      out.write("      <li style=\"line-height:20%\" class=\"footerlistyle\"><a href=\"\" style=\"text-decoration: none\" class=\"footerastyle\">1:1문의</a></li><br>\n");
      out.write("      ▶ 문의메일: TeamProject@Tripgo.co.kr<br>\n");
      out.write("      ▶ 대표번호: 010-0000-0000<br>\n");
      out.write("      </span>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <ul class=\"nav col-md-4 justify-content-end list-unstyled d-flex\">\n");
      out.write("      <li class=\"ms-3\"><a class=\"text-muted\" href=\"https://www.facebook.com/?locale=ko_KR\"><img src=\"../resources/image/Facebook.png\" alt=\"\" width=\"30\" height=\"30\"></a></li>\n");
      out.write("      <li class=\"ms-3\"><a class=\"text-muted\" href=\"https://www.instagram.com/\"><img src=\"../resources/image/instagram.png\" alt=\"\" width=\"30\" height=\"30\"></a></li>\n");
      out.write("      <li class=\"ms-3\"><a class=\"text-muted\" href=\"https://twitter.com/?lang=ko\"><img src=\"../resources/image/twiiter.png\" alt=\"\" width=\"30\" height=\"30\"></a></li>\n");
      out.write("      <li class=\"ms-3\"><a class=\"text-muted\" href=\"https://www.kakaocorp.com/page/service/service/KakaoTalk\"><img src=\"../resources/image/kakaotalk.png\" alt=\"\" width=\"30\" height=\"30\"></a></li>\n");
      out.write("    </ul>\n");
      out.write("  </footer>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>\n");
      out.write("    ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_sec_005fauthorize_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f0 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f0_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f0.setParent(null);
      // /WEB-INF/views/board/../includes/header1.jsp(42,40) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f0.setAccess("isAnonymous()");
      int _jspx_eval_sec_005fauthorize_005f0 = _jspx_th_sec_005fauthorize_005f0.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write(" <!-- 로그인 안했을 때 표시 -->\n");
        out.write("                                        <li><a href=\"/customLogin\">로그인</a></li>\n");
        out.write("                                        ");
      }
      if (_jspx_th_sec_005fauthorize_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f0);
      _jspx_th_sec_005fauthorize_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f0, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthorize_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f1 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f1_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f1.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f1.setParent(null);
      // /WEB-INF/views/board/../includes/header1.jsp(45,40) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f1.setAccess("isAuthenticated()");
      int _jspx_eval_sec_005fauthorize_005f1 = _jspx_th_sec_005fauthorize_005f1.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write(" <!--  로그인 하였을 때 표시 -->\n");
        out.write("                                        <li><a href=\"/customLogout\">로그아웃</a></li>\n");
        out.write("                                        ");
      }
      if (_jspx_th_sec_005fauthorize_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f1);
      _jspx_th_sec_005fauthorize_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f1, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthentication_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authentication
    org.springframework.security.taglibs.authz.AuthenticationTag _jspx_th_sec_005fauthentication_005f0 = (org.springframework.security.taglibs.authz.AuthenticationTag) _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fvar_005fproperty_005fnobody.get(org.springframework.security.taglibs.authz.AuthenticationTag.class);
    boolean _jspx_th_sec_005fauthentication_005f0_reused = false;
    try {
      _jspx_th_sec_005fauthentication_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthentication_005f0.setParent(null);
      // /WEB-INF/views/board/get.jsp(48,4) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthentication_005f0.setProperty("principal");
      // /WEB-INF/views/board/get.jsp(48,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthentication_005f0.setVar("pinfo");
      int _jspx_eval_sec_005fauthentication_005f0 = _jspx_th_sec_005fauthentication_005f0.doStartTag();
      if (_jspx_th_sec_005fauthentication_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fvar_005fproperty_005fnobody.reuse(_jspx_th_sec_005fauthentication_005f0);
      _jspx_th_sec_005fauthentication_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthentication_005f0, _jsp_getInstanceManager(), _jspx_th_sec_005fauthentication_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthorize_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f2 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f2_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f2.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f2.setParent(null);
      // /WEB-INF/views/board/get.jsp(49,4) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f2.setAccess("isAuthenticated()");
      int _jspx_eval_sec_005fauthorize_005f2 = _jspx_th_sec_005fauthorize_005f2.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\r\n");
        out.write("					");
        if (_jspx_meth_c_005fif_005f0(_jspx_th_sec_005fauthorize_005f2, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("				");
      }
      if (_jspx_th_sec_005fauthorize_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f2);
      _jspx_th_sec_005fauthorize_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f2, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_sec_005fauthorize_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sec_005fauthorize_005f2);
      // /WEB-INF/views/board/get.jsp(50,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pinfo.username eq board.member_email}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				<button data-oper='modify' class=\"btn btn-primary\" style=\"margin-top: 20px;\">수정하기</button>\r\n");
          out.write("					");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("    ");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("    ");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write('\r');
          out.write('\n');
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/board/get.jsp(57,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${isLiked}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("            <button id=\"likeButton\" class=\"btn btn-light\"  style=\"margin-top: 20px; margin-right: 480px; float: right;\"><img alt=\"\" src=\"/resources/image/unlikeboard.png\"></button>\r\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("            <button id=\"likeButton\" class=\"btn btn-light\"  style=\"margin-top: 20px; margin-right: 480px; float: right;\"><img alt=\"\" src=\"/resources/image/likeboard.png\"></button>\r\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthorize_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f3 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f3_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f3.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f3.setParent(null);
      // /WEB-INF/views/board/get.jsp(88,1) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f3.setAccess("isAuthenticated()");
      int _jspx_eval_sec_005fauthorize_005f3 = _jspx_th_sec_005fauthorize_005f3.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\r\n");
        out.write("	        <button id=\"addReplyBtn\" class=\"btn btn-white\" style=\"float: right;\"><img alt=\"\" src=\"/resources/image/newreply.png\"></button> \r\n");
        out.write("	 ");
      }
      if (_jspx_th_sec_005fauthorize_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f3);
      _jspx_th_sec_005fauthorize_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f3, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthorize_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f4 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f4_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f4.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f4.setParent(null);
      // /WEB-INF/views/board/get.jsp(213,1) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f4.setAccess("isAuthenticated()");
      int _jspx_eval_sec_005fauthorize_005f4 = _jspx_th_sec_005fauthorize_005f4.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\r\n");
        out.write("    // 주어진 문자열에서 이메일 주소를 파싱하여 member_email 변수에 할당\r\n");
        out.write("    member_email = '");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pinfo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("'.split('member_email=')[1].split(',')[0];\r\n");
      }
      if (_jspx_th_sec_005fauthorize_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f4);
      _jspx_th_sec_005fauthorize_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f4, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f4_reused);
    }
    return false;
  }
}
