/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-04-16 07:37:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/C:/java/Spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Odga/WEB-INF/lib/spring-webmvc-5.2.7.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1591652570000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-5.2.7.RELEASE.jar", Long.valueOf(1712115647224L));
    _jspx_dependants.put("jar:file:/C:/java/Spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Odga/WEB-INF/lib/jstl-1.2.jar!/META-INF/c-1_0-rt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1712112365428L));
    _jspx_dependants.put("jar:file:/C:/java/Spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Odga/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!doctype html>\n");
      out.write("<html class=\"no-js\" lang=\"zxx\">\n");
      out.write("<head>\n");
      out.write("   <title>Odga.com</title>\n");
      out.write("   <!-- Bootstrap Core CSS -->\n");
      out.write("   <link href=\"../assets/css/login.css\" rel=\"stylesheet\">\n");
      out.write("   <link href=\"assets/css/profile2.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<style>\n");
      out.write(".swal-button{background-color:#ff3d1c}.swal-button:not([disabled]):hover{background-color:#ff5235}.swal-button:hover{background-color:#ff5235}.swal-footer{text-align:center}.swal-button:focus{box-shadow:none}\n");
      out.write("p:hover { color: #8fa1c7; }\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<!-- Logo -->\n");
      out.write(" <div style=\"width: 10%;min-width: 9rem;\">\n");
      out.write("     <a href=\"index.do\"><img src=\"assets/img/logo/logo_b.png\" alt=\"\" style=\"max-width: 100%;\"></a>\n");
      out.write(" </div>\n");
      out.write("<!-- 로그인  -->\n");
      out.write("<p class=\"tip\"></p>\n");
      out.write("<div class=\"cont\">\n");
      out.write("  <div class=\"form sign-in\">\n");
      out.write("   <form id=\"LoginS\" name=\"loginS\"  >    \n");
      out.write("       <h2>여행시작하기,</h2>\n");
      out.write("       <input type=\"hidden\" id=\"RSAModulus\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${RSAModulus}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /><!-- 서버에서 전달한값 세팅. -->\n");
      out.write("      <input type=\"hidden\" id=\"RSAExponent\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${RSAExponent}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /><!-- 서버에서 전달한값 세팅 -->\n");
      out.write("       <label>\n");
      out.write("         <span>이메일</span>\n");
      out.write("         <input type=\"text\" name=\"m_email\" id=\"l_email\" required=\"required\"/>\n");
      out.write("       </label>\n");
      out.write("       <label>\n");
      out.write("         <span>비밀번호</span>\n");
      out.write("         <input type=\"password\" name=\"m_pwd\" id=\"l_pwd\" required=\"required\"/>\n");
      out.write("       </label>\n");
      out.write("      <a href=\"findIdPwd\">\n");
      out.write("          <p class=\"forgot-pass\" style=\"text-decoration-line: underline;\">이메일 또는 비밀번호가 기억이 안나시나요?</p>\n");
      out.write("       </a>\n");
      out.write("   \n");
      out.write("       <button type=\"button\" id=\"ms_login\" class=\"submit\" onclick=\"loginCheck()\" >시작 </button><!-- class=\"submit\" onclick=\"loginCheck()\" -->\n");
      out.write("       <!-- 네이버 로그인 창으로 이동 -->\n");
      out.write("      <div id=\"naver_id_login\" style=\"text-align:center\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("      <img style=\"max-height: 40px;border-radius: 30px;width: 45%;\" width=\"223\" src=\"https://developers.naver.com/doc/review_201802/CK_bEFnWMeEBjXpQ5o8N_20180202_7aot50.png\"/></a></div>\n");
      out.write("      <br>\n");
      out.write("  </form>\n");
      out.write("  </div>\n");
      out.write("  \n");
      out.write("  <div class=\"sub-cont\">\n");
      out.write("    <div class=\"img\">\n");
      out.write("      <div class=\"img__text m--up\">\n");
      out.write("        <h2>처음 오셨나요?</h2>\n");
      out.write("        <p></p>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"img__text m--in\">\n");
      out.write("        <h2>가입하기</h2>\n");
      out.write("        <p></p>\n");
      out.write("      </div>\n");
      out.write("      \n");
      out.write("      <div class=\"img__btn\">\n");
      out.write("        <span class=\"m--up\">가입하기</span>\n");
      out.write("        <span class=\"m--in\">로그인 하기</span>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <!-- 회원가입  -->\n");
      out.write("    \n");
      out.write("    <script>\n");
      out.write("\n");
      out.write("   //아이디와 비밀번호가 맞지 않을 경우 가입버튼 비활성화를 위한 변수설정\n");
      out.write("    var idCheck = 0;\n");
      out.write("    var pwdCheck = 0;\n");
      out.write("    \n");
      out.write("    //아이디 체크하여 가입버튼 비활성화, 중복확인.\n");
      out.write("    function checkId() {\n");
      out.write("             \n");
      out.write("        //var inputed = $('.m_email').val();\n");
      out.write("        var inputed = $(\"#email\").val();\n");
      out.write("      \n");
      out.write("        $.ajax({\n");
      out.write("            data : {\n");
      out.write("                m_email : $(\"#email\").val()\n");
      out.write("            },\n");
      out.write("            type : \"post\",\n");
      out.write("            url : \"checkId.jy\",\n");
      out.write("            success : function(data) {\n");
      out.write("               \n");
      out.write("                if(inputed==\"\" && data=='0') {\n");
      out.write("                    $(\".submit\").prop(\"disabled\", true);\n");
      out.write("                    $(\".submit\").css(\"background-color\", \"#aaaaaa\");\n");
      out.write("                    $(\"#email\").css(\"background-color\", \"#FFCECE\");\n");
      out.write("                    idCheck = 0;\n");
      out.write("                } else if (data == '0') {\n");
      out.write("                    $(\"#email\").css(\"background-color\", \"#B0F6AC\").css(\"color\",\"black\");\n");
      out.write("                    idCheck = 1;\n");
      out.write("                    if(idCheck==1 && pwdCheck == 1) {\n");
      out.write("                        $(\".submit\").prop(\"disabled\", false);\n");
      out.write("                        $(\".submit\").css(\"background-color\", \"#4CAF50\");\n");
      out.write("\n");
      out.write("                    }\n");
      out.write("                } else if (data == '1') {\n");
      out.write("                    $(\".submit\").prop(\"disabled\", true);\n");
      out.write("                    $(\".submit\").css(\"background-color\", \"#aaaaaa\");\n");
      out.write("                    $(\"#email\").css(\"background-color\", \"#FFCECE\").css(\"color\",\"black\");\n");
      out.write("                    idCheck = 0;\n");
      out.write("                }else{\n");
      out.write("                 salert('회원가입 완료');\n");
      out.write("                }\n");
      out.write("                              \n");
      out.write("               console.log(data);\n");
      out.write("               \n");
      out.write("            },\n");
      out.write("            // 밑에 라인 참조 시작\n");
      out.write("            type : \"POST\",\n");
      out.write("            // 밑에 라인 참조 종료\n");
      out.write("            error : function(error) {\n");
      out.write("               console.log(error);\n");
      out.write("               salert(\"에러\");\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    // 패스워드 확인\n");
      out.write("    function checkPwd() {\n");
      out.write("        var inputed = $(\"#m_pwd\").val();\n");
      out.write("        var reinputed = $(\"#m_pwdcheck\").val();\n");
      out.write("        if(reinputed==\"\" && (inputed != reinputed || inputed == reinputed)){\n");
      out.write("            $(\".submit\").prop(\"disabled\", false);\n");
      out.write("            $(\"#m_pwdcheck\").css(\"background-color\", \"#FFCECE\");\n");
      out.write("        }\n");
      out.write("        else if (inputed == reinputed) {\n");
      out.write("            $(\"#m_pwdcheck\").css(\"background-color\", \"#B0F6AC\").css(\"color\",\"black\");\n");
      out.write("            pwdCheck = 1;\n");
      out.write("            if(idCheck==1 && pwdCheck == 1) {      \n");
      out.write("            }\n");
      out.write("        } else if (inputed != reinputed) {\n");
      out.write("            pwdCheck = 0;\n");
      out.write("            $(\"#m_pwdcheck\").css(\"background-color\", \"#FFCECE\").css(\"color\",\"black\");\n");
      out.write("       }\n");
      out.write("    }\n");
      out.write("   \n");
      out.write("    // email\n");
      out.write("    function emailAuth(){\n");
      out.write("       \n");
      out.write("       if ( confirm(\"인증 이메일을 발송중입니다.\") ) {\n");
      out.write("          \n");
      out.write("            $.ajax({\n");
      out.write("                data : {\n");
      out.write("                   m_email : $(\"#email\").val()\n");
      out.write("                },\n");
      out.write("                type : \"post\",\n");
      out.write("                url : \"/sign-up\",\n");
      out.write("                success : function(data) {\n");
      out.write("                   salert(\"인증코드를 확인하세요.\");\n");
      out.write("                   console.log(data);\n");
      out.write("                   $(\"#email_auth_chk\").css(\"display\",\"block\");\n");
      out.write("                },\n");
      out.write("                error : function(error) {\n");
      out.write("                   console.log(error);\n");
      out.write("                   salert(\"이메일을 입력해주세요.\");\n");
      out.write("                }\n");
      out.write("            });\n");
      out.write("          \n");
      out.write("       } else {\n");
      out.write("          salert(\"다시 시도해주세요.\");\n");
      out.write("       }\n");
      out.write("       \n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function emailAuth_key(){\n");
      out.write("       \n");
      out.write("        $.ajax({\n");
      out.write("            data : {\n");
      out.write("               Authkey : $(\"#email_AuthKey\").val()\n");
      out.write("            },\n");
      out.write("            type : \"post\",\n");
      out.write("            url : \"/emailConfirm\",\n");
      out.write("            success : function(data) {\n");
      out.write("               if(data==\"no\"){\n");
      out.write("                  salert(\"인증실패\");\n");
      out.write("                  return false;\n");
      out.write("               }else{\n");
      out.write("               salert(\"인증성공하였습니다.\");\n");
      out.write("               console.log(data);\n");
      out.write("               $(\"#e_check\").val(\"checkcheck\");\n");
      out.write("               $(\"#email_auth_chk\").css(\"display\",\"none\");\n");
      out.write("               $(\"#submitBtn\").prop(\"disabled\", false);\n");
      out.write("               $(\"#submitBtn\").css(\"background-color\", \"#4CAF50\");\n");
      out.write("               }\n");
      out.write("            },\n");
      out.write("            error : function(error) {\n");
      out.write("               console.log(error);\n");
      out.write("               salert(\"에러\");\n");
      out.write("               salert(\"이메일인증을 다시하세요\");\n");
      out.write("               $(\"#email_AuthKey\").val(\"\");\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    </script>\n");
      out.write("   \n");
      out.write("   <div class=\"form sign-up\">\n");
      out.write("    <form action=\"join.do\" name=\"joinFrm\" method=\"post\" id=\"joinS\" enctype=\"multipart/form-data\"  >\n");
      out.write("    <input type=\"hidden\" name=\"e_check\" id=\"e_check\" value=\"\"/>\n");
      out.write("      <h2>두근두근 여행,</h2>\n");
      out.write("      <label>\n");
      out.write("        <span>이메일</span>\n");
      out.write("        <input type=\"text\" name=\"m_email\" id=\"email\" oninput=\"checkId()\" required/>\n");
      out.write("        <input type='button' value='이메일인증'  onclick=\"emailAuth()\">\n");
      out.write("      </label>\n");
      out.write("     \n");
      out.write("      <label>\n");
      out.write("         <div id=\"email_auth_chk\" style=\"display:none\">\n");
      out.write("           <input type=\"text\" name=\"m_email_AuthKey\" id=\"email_AuthKey\" />\n");
      out.write("           <h2><input type='button' value='인증하기' onclick=\"emailAuth_key()\" /></h2>\n");
      out.write("         </div> \n");
      out.write("      </label>     \n");
      out.write("      \n");
      out.write("      <label>\n");
      out.write("        <span>이름</span>\n");
      out.write("        <input type=\"text\" name=\"m_name\" id=\"m_name\"  required/>\n");
      out.write("      </label>\n");
      out.write("      <label>\n");
      out.write("        <span>비밀번호</span>\n");
      out.write("        <input type=\"password\" name=\"m_pwd\" id=\"m_pwd\" oninput=\"checkPwd()\" required/>\n");
      out.write("      </label>\n");
      out.write("      \n");
      out.write("      <label>\n");
      out.write("        <span>비밀번호 확인</span>\n");
      out.write("        <input type=\"password\" name=\"m_pwdcheck\" id=\"m_pwdcheck\" oninput=\"checkPwd()\" />\n");
      out.write("      </label>\n");
      out.write("       \n");
      out.write("      <label>\n");
      out.write("        <span>휴대폰번호</span>\n");
      out.write("        <input type=\"text\" name=\"m_phone\" id=\"m_phone\"  required/>\n");
      out.write("      </label>\n");
      out.write("      \n");
      out.write("      <label>\n");
      out.write("      <span>생년월일</span>\n");
      out.write("        <input type=\"date\" name=\"m_birth\" id=\"m_birth\"  required/>\n");
      out.write("      </label>\n");
      out.write("      \n");
      out.write("      <div id=\"reg_gender\" style=\"display:flex;justify-content:center; margin: 15px;\">\n");
      out.write("         <input type=\"radio\" value=\"male\" id=\"male\" name=\"m_gender\" checked style=\"width:auto;\"/>\n");
      out.write("         <label for=\"squaredFour\" style=\"margin:0;width:50px;\">남자</label>\n");
      out.write("         <input type=\"radio\" value=\"female\" id=\"female\" name=\"m_gender\" checked style=\"width:auto;\"/>\n");
      out.write("         <label for=\"squaredFour\" style=\"margin:0;width:50px;\">여자</label>\n");
      out.write("      </div>\n");
      out.write("      <label>\n");
      out.write("      <span>자기소개</span>\n");
      out.write("        <input type=\"text\" name=\"m_about\" id=\"m_about\"/>\n");
      out.write("      </label>\n");
      out.write("      \n");
      out.write("      <label>\n");
      out.write("        <span>프로필사진등록</span>\n");
      out.write("        <input type=\"file\" name=\"file\" id=\"m_fname\"/>\n");
      out.write("      </label>\n");
      out.write("    <div class=\"row\">\n");
      out.write("      <button type=\"button\" id=\"submitBtn\" class=\"submit\" style=\"background:#aaaaaa \" disabled=\"\" >가입하기</button>\n");
      out.write("    </div>\n");
      out.write("    </form>\n");
      out.write("   </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("<script src=\"../assets/js/login.js\"></script>\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.5.1.min.js\" integrity=\"sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=\" crossorigin=\"anonymous\"></script>\n");
      out.write("<script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\n");
      out.write("<!-- RSA 자바스크립트 라이브러리 -->\n");
      out.write("<script type=\"text/javascript\" src=\"../js/RSA/jsbn.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"../js/RSA/rsa.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"../js/RSA/prng4.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"../js/RSA/rng.js\"></script>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("function salert(text){\n");
      out.write("   swal({\n");
      out.write("     text: text,\n");
      out.write("     buttons:{true:\"확인\"},\n");
      out.write("     });\n");
      out.write("}\n");
      out.write("document.getElementById('submitBtn').onclick = function(){\n");
      out.write("   var l = document.joinFrm; \n");
      out.write("   \n");
      out.write("   if (l.m_email.value == \"\" || l.m_pwd.value == \"\") {\n");
      out.write("       salert(\"이메일 및 비밀번호를 입력해주세요.\");\n");
      out.write("       l.m_email.focus();\n");
      out.write("       return false;\n");
      out.write("   }else if (l.m_email_AuthKey.value == \"\") {\n");
      out.write("       salert(\"이메일 인증을 해주세요.\");\n");
      out.write("       l.m_email_AuthKey.focus();\n");
      out.write("       return false;\n");
      out.write("   }else if (l.m_name.value == \"\") {\n");
      out.write("       salert(\"이름을 입력해주세요.\");\n");
      out.write("       l.m_name.focus();\n");
      out.write("       return false;\n");
      out.write("   }else if (l.m_phone.value == \"\") {\n");
      out.write("       salert(\"전화번호을 입력해주세요.\");\n");
      out.write("       l.m_phone.focus();\n");
      out.write("       return false;\n");
      out.write("   }else if (l.m_birth.value == \"\") {\n");
      out.write("       salert(\"생년월일을 입력해주세요.\");\n");
      out.write("       l.m_birth.focus();\n");
      out.write("       return false;\n");
      out.write("   }else{\n");
      out.write("         swal({\n");
      out.write("            text: \"회원가입이 완료 되었습니다.\",\n");
      out.write("            buttons:{\"확인\":true},\n");
      out.write("            }).then((value) => {\n");
      out.write("               if(value){\n");
      out.write("                  document.joinFrm.submit();\n");
      out.write("               }\n");
      out.write("            });\n");
      out.write("      }\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("<script>\n");
      out.write("$(document).ready(function() {   \n");
      out.write("    // ID를 alpreah_input로 가지는 곳에서 키를 누를 경우\n");
      out.write("    $(\"#l_email\").keydown(function(key) {\n");
      out.write("        //키의 코드가 13번일 경우 (13번은 엔터키)\n");
      out.write("        if (key.keyCode == 13) {\n");
      out.write("           $(\"#ms_login\").click();\n");
      out.write("        }\n");
      out.write("    });\n");
      out.write("    $(\"#l_pwd\").keydown(function(key) {\n");
      out.write("        //키의 코드가 13번일 경우 (13번은 엔터키)\n");
      out.write("        if (key.keyCode == 13) {\n");
      out.write("           $(\"#ms_login\").click();\n");
      out.write("        }\n");
      out.write("    });\n");
      out.write("});\n");
      out.write("</script>\n");
      out.write("<script>\n");
      out.write("   \n");
      out.write("    function loginCheck(){\n");
      out.write("       \n");
      out.write("      var l = document.loginS; \n");
      out.write("      \n");
      out.write("      if (l.m_email.value == \"\" && l.m_pwd.value == \"\") {\n");
      out.write("          salert(\"이메일 및 비밀번호를 입력해주세요.\");\n");
      out.write("          l.m_email.focus();\n");
      out.write("          return false;\n");
      out.write("      }\n");
      out.write("      /* $.ajax({                             // ajax 함수를 실행하는 선언문입니다. jquery에서 가져와\n");
      out.write("         type : \"POST\",                   // method 구분입니다. 파라미터는 GET, POST 문자열 구문으로 작성합니다.\n");
      out.write("            url : \"/checkLogin.jy\",          // url을 입력합니다. 예를들어, requestMapping=login.do 컨트롤러 연동이 필요할경우 login.do 를 문자열로 작성 \n");
      out.write("            data : {                        // 모델앤뷰 객체에 담길 data 파라미터입니다. VO 로 담겨서 컨트롤러로 이동된다고 생각하세요\n");
      out.write("                m_email : $(\"#l_email\").val()\n");
      out.write("               ,m_pwd   : $(\"#l_pwd\").val()\n");
      out.write("            },\n");
      out.write("            success : function(data) {       // ajax가 성공할 경우 해당 구문으로 진입합니다.\n");
      out.write("               // 로그인 성공\n");
      out.write("               \n");
      out.write("               if ( data == \"1\" ){\n");
      out.write("                  l.submit();\n");
      out.write("               } else {\n");
      out.write("                  salert(\"이메일 또는 비밀번호를 다시 확인해주세요.\");\n");
      out.write("                  return;\n");
      out.write("               }\n");
      out.write("            },\n");
      out.write("            error : function(error) {        // ajax가 오류날 경우 해당 구문으로 진입합니다.\n");
      out.write("               \n");
      out.write("               // 이제 checkLogin.jy 에서 아이디, 비밀번호 검증하고 true false 리턴줘서 처리하면됨\n");
      out.write("               salert(\"서비스에러발생\");\n");
      out.write("\n");
      out.write("            }\n");
      out.write("        }); */\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("</script>\n");
      out.write("<script>\n");
      out.write("$(document).ready(function() {   \n");
      out.write("    // ID를 alpreah_input로 가지는 곳에서 키를 누를 경우\n");
      out.write("    $(\"#l_email\").keydown(function(key) {\n");
      out.write("        //키의 코드가 13번일 경우 (13번은 엔터키)\n");
      out.write("        if (key.keyCode == 13) {\n");
      out.write("           loginCheck()\n");
      out.write("        }\n");
      out.write("    });\n");
      out.write("    $(\"#l_pwd\").keydown(function(key) {\n");
      out.write("        //키의 코드가 13번일 경우 (13번은 엔터키)\n");
      out.write("        if (key.keyCode == 13) {\n");
      out.write("           loginCheck()\n");
      out.write("        }\n");
      out.write("    });\n");
      out.write("});\n");
      out.write("</script>\n");
      out.write("<script>\n");
      out.write("$(\"#ms_login\").click(function(){\n");
      out.write("   //사용자 계정정보 암호화전 평문\n");
      out.write("   var uemail = $(\"#l_email\").val();\n");
      out.write("   var pwd = $(\"#l_pwd\").val();\n");
      out.write("   \n");
      out.write("   //alert(uemail +\"##\"+ pwd);\n");
      out.write("   //RSA 암호화 생성\n");
      out.write("   var rsa = new RSAKey();\n");
      out.write("   rsa.setPublic($(\"#RSAModulus\").val(), $(\"#RSAExponent\").val());\n");
      out.write("   \n");
      out.write("   //사용자 계정정보를 암호화 처리\n");
      out.write("   uemail = rsa.encrypt(uemail);\n");
      out.write("   pwd = rsa.encrypt(pwd); \n");
      out.write("   //alert(uemail +\"##\"+ pwd);\n");
      out.write("   $.ajax({ \n");
      out.write("        type: \"POST\",  \n");
      out.write("        url: \"login.proc\",  \n");
      out.write("        data: {m_email :uemail, m_pwd: pwd},  //사용자 암호화된 계정정보를 서버로 전송\n");
      out.write("        dataType:\"json\",\n");
      out.write("        success: function(msg){    \n");
      out.write("          \n");
      out.write("           if(msg.state == \"true\")\n");
      out.write("           {\n");
      out.write("              location.href = \"../\"; \n");
      out.write("           }\n");
      out.write("           else if(msg.state == \"false\")\n");
      out.write("           {\n");
      out.write("             salert(\"이메일 또는 비밀번호를 다시 확인해주세요.\");\n");
      out.write("           }\n");
      out.write("           else\n");
      out.write("           {\n");
      out.write("             salert(\"잘못된 경로로 접근하였습니다. 암호화 인증에 실패하였습니다.\"); \n");
      out.write("           } \n");
      out.write("        } \n");
      out.write("   });\n");
      out.write("});\n");
      out.write("</script>\n");
      out.write("</html>    \n");
      out.write("\n");
      out.write("<!-- jQuery-->\n");
      out.write("        ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
