/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-05-27 05:56:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/C:/java/Spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Trip03/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/includes/header1.jsp", Long.valueOf(1716535517938L));
    _jspx_dependants.put("/WEB-INF/lib/spring-security-taglibs-5.2.7.RELEASE.jar", Long.valueOf(1714376254473L));
    _jspx_dependants.put("jar:file:/C:/java/Spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Trip03/WEB-INF/lib/spring-security-taglibs-5.2.7.RELEASE.jar!/META-INF/security.tld", Long.valueOf(1602058062000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1712112365428L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("\n");
      out.write("\n");
      out.write("    \n");
      out.write("        \n");
      out.write("<!DOCTYPE html>\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"utf-8\">\n");
      out.write("        <title>Flex - Responsive HTML Template</title>\n");
      out.write("    	<meta name=\"description\" content=\"\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<!-- \n");
      out.write("Flex Template \n");
      out.write("http://www.templatemo.com/tm-406-flex\n");
      out.write("-->\n");
      out.write("        <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'>\n");
      out.write("        <link rel=\"stylesheet\" href=\"/resources/css/bootstrap.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"/resources/css/font-awesome.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"/resources/css/animate.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"/resources/css/templatemo_misc.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"/resources/css/templatemo_style.css\">\n");
      out.write("\n");
      out.write("        <script src=\"/resources/js/vendor/modernizr-2.6.1-respond-1.1.0.min.js\"></script>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("      <div class=\"site-header\">\n");
      out.write("                <div class=\"main-header\">\n");
      out.write("                        <div id=\"menu-wrapper\">\n");
      out.write("                            <div class=\"row\">\n");
      out.write("                                <div class=\"logo-wrapper col-md-2 col-sm-2\">\n");
      out.write("                                    <h1>\n");
      out.write("                                        <a href=\"/main\">TRIP</a>\n");
      out.write("                                    </h1>\n");
      out.write("                                </div> <!-- /.logo-wrapper -->\n");
      out.write("                                <div class=\"col-md-10 col-sm-10 main-menu text-right\">\n");
      out.write("                                    <ul class=\"menu\">\n");
      out.write("                                        <li class=\"active\"><a href=\"/main\">메인 홈</a></li>\n");
      out.write("                                        <li><a href=\"#portfolio\">여행지</a></li>\n");
      out.write("                                        <li><a href=\"#services\">여행 계획</a></li>\n");
      out.write("                                        <li><a href=\"/board/list\">게시판</a> </li>\n");
      out.write("                                        <li><a href=\"/member/mypage\">마이페이지</a> </li>\n");
      out.write("                                        <li><a href=\"#\">고객 센터</a></li> \n");
      out.write("                                        ");
      if (_jspx_meth_sec_005fauthorize_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                                        ");
      if (_jspx_meth_sec_005fauthorize_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                                    </ul>                                    \n");
      out.write("                                </div> <!-- /.main-menu -->\n");
      out.write("                            </div> <!-- /.row -->\n");
      out.write("                        </div> <!-- /#menu-wrapper -->                        \n");
      out.write("                </div> <!-- /.main-header -->\n");
      out.write("            </div> <!-- /.site-header -->\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js\"></script>        ");
      out.write("\n");
      out.write("    <body>\n");
      out.write("\n");
      out.write("        <div class=\"site-main\" id=\"sTop\">\n");
      out.write("            <div class=\"site-slider\">\n");
      out.write("                <div class=\"slider\">\n");
      out.write("                    <div class=\"flexslider\">\n");
      out.write("                        <ul class=\"slides\">\n");
      out.write("                            <li>\n");
      out.write("                                <div class=\"overlay\"></div>\n");
      out.write("                                <img src=\"/resources/images/화성4.jpg\" alt=\"\">\n");
      out.write("                                <div class=\"slider-caption visible-md visible-lg\">\n");
      out.write("                                    <h2>원하는 곳을 간편하게</h2>\n");
      out.write("                                    <p>Where you want to go, easily</p>\n");
      out.write("                                      <ul class=\"menu-first\">\n");
      out.write("                                    <li><a href=\"#portfolio\" class=\"slider-btn\">계획 작성하기</a></li>\n");
      out.write("                                    </ul>\n");
      out.write("                                </div>\n");
      out.write("                            </li>\n");
      out.write("                            <li>\n");
      out.write("                                <div class=\"overlay\"></div>\n");
      out.write("                                <img src=\"/resources/images/시티뷰.jpg\" alt=\"\">\n");
      out.write("                                <div class=\"slider-caption visible-md visible-lg\">\n");
      out.write("                                    <h2>이번 휴양지는 어디로</h2>\n");
      out.write("                                    <p>Where is this vacation spot?</p>\n");
      out.write("                                    <a href=\"#\" class=\"slider-btn\">회원 결제하기</a>\n");
      out.write("                                </div>\n");
      out.write("                            </li>\n");
      out.write("                            <li>\n");
      out.write("                                <div class=\"overlay\"></div>\n");
      out.write("                                <img src=\"/resources/images/서울.jpg\" alt=\"\">\n");
      out.write("                                <div class=\"slider-caption visible-md visible-lg\">\n");
      out.write("                                    <h2>마음에 드는 곳으로</h2>\n");
      out.write("                                    <p>High standard work</p>\n");
      out.write("                                    <ul class=\"menu-first\">\n");
      out.write("                                    <li><a href=\"#portfolio\" class=\"slider-btn\">계획 작성하기</a></li>\n");
      out.write("                                    </ul>\n");
      out.write("                                </div>\n");
      out.write("                            </li>\n");
      out.write("                        </ul>\n");
      out.write("                    </div> <!-- /.flexslider -->\n");
      out.write("                </div> <!-- /.slider -->\n");
      out.write("            </div> <!-- /.site-slider -->\n");
      out.write("        </div> <!-- /.site-main -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("        <div class=\"content-section\" id=\"portfolio\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                    <div class=\"heading-section col-md-12 text-center\">\n");
      out.write("                        <h2>어디로 여행을 떠나시나요?</h2>\n");
      out.write("                        <p>Where are you leaving</p>\n");
      out.write("                    </div> <!-- /.heading-section -->\n");
      out.write("                 <!-- /.row -->\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"portfolio-item col-md-3 col-sm-7\">\n");
      out.write("                        <div class=\"portfolio-thumb\">\n");
      out.write("                            <img src=\"/resources/images/gallery/제주도.jpg\" alt=\"\">\n");
      out.write("                            <h1 class=\"text-sm font-medium truncate md:text-2xl font-Montserrat\">JEJU</h1>\n");
      out.write("<h2 class=\"mb-2 text-xs font-thin truncate md:text-sm\">대한민국 제주</h2>\n");
      out.write("                        </div> <!-- /.portfolio-thumb -->\n");
      out.write("                    </div> <!-- /.portfolio-item -->\n");
      out.write("                    <div class=\"portfolio-item col-md-3 col-sm-7\">\n");
      out.write("                        <div class=\"portfolio-thumb\">\n");
      out.write("                            <img src=\"/resources/images/gallery/서울.jpg\" alt=\"\">\n");
      out.write("                            <h1 class=\"text-sm font-medium truncate md:text-2xl font-Montserrat\">SEOUL</h1>\n");
      out.write("<h2 class=\"mb-2 text-xs font-thin truncate md:text-sm\">대한민국 서울</h2>\n");
      out.write("                        </div> <!-- /.portfolio-thumb -->\n");
      out.write("                    </div> <!-- /.portfolio-item -->\n");
      out.write("                    \n");
      out.write("                    <div class=\"portfolio-item col-md-3 col-sm-7\">\n");
      out.write("                        <div class=\"portfolio-thumb\">\n");
      out.write("                            <img src=\"/resources/images/gallery/부산.jpg\" alt=\"\">\n");
      out.write("                            <h1 class=\"text-sm font-medium truncate md:text-2xl font-Montserrat\">BUSAN</h1>\n");
      out.write("<h2 class=\"mb-2 text-xs font-thin truncate md:text-sm\">대한민국 부산</h2>\n");
      out.write("                        </div> <!-- /.portfolio-thumb -->\n");
      out.write("                    </div> <!-- /.portfolio-item -->\n");
      out.write("                    <div class=\"portfolio-item col-md-3 col-sm-7\">\n");
      out.write("                        <div class=\"portfolio-thumb\">\n");
      out.write("                            <img src=\"/resources/images/gallery/경주.jpg\" alt=\"\">\n");
      out.write("                            <h1 class=\"text-sm font-medium truncate md:text-2xl font-Montserrat\">GYEONGJU</h1>\n");
      out.write("<h2 class=\"mb-2 text-xs font-thin truncate md:text-sm\">대한민국 경주</h2>\n");
      out.write("                        </div> <!-- /.portfolio-thumb -->\n");
      out.write("                    </div> <!-- /.portfolio-item -->\n");
      out.write("                       <div class=\"portfolio-item col-md-3 col-sm-7\">\n");
      out.write("                        <div class=\"portfolio-thumb\">\n");
      out.write("                            <img src=\"/resources/images/gallery/강릉.jpg\" alt=\"\">\n");
      out.write("                            <h1 class=\"text-sm font-medium truncate md:text-2xl font-Montserrat\">GANGNEUNG</h1>\n");
      out.write("<h2 class=\"mb-2 text-xs font-thin truncate md:text-sm\">대한민국 강릉</h2>\n");
      out.write("                        </div> <!-- /.portfolio-thumb -->\n");
      out.write("                    </div> <!-- /.portfolio-item -->\n");
      out.write("                       <div class=\"portfolio-item col-md-3 col-sm-7\">\n");
      out.write("                        <div class=\"portfolio-thumb\">\n");
      out.write("                            <img src=\"/resources/images/gallery/여수.jpg\" alt=\"\">\n");
      out.write("                            <h1 class=\"text-sm font-medium truncate md:text-2xl font-Montserrat\">YEOSU</h1>\n");
      out.write("<h2 class=\"mb-2 text-xs font-thin truncate md:text-sm\">대한민국 여수</h2>\n");
      out.write("                        </div> <!-- /.portfolio-thumb -->\n");
      out.write("                    </div> <!-- /.portfolio-item -->\n");
      out.write("                       <div class=\"portfolio-item col-md-3 col-sm-7\">\n");
      out.write("                        <div class=\"portfolio-thumb\">\n");
      out.write("                            <img src=\"/resources/images/gallery/거제통영.jpg\" alt=\"\">\n");
      out.write("                            <h1 class=\"text-sm font-medium truncate md:text-2xl font-Montserrat\">GEOJETONGYEONG</h1>\n");
      out.write("<h2 class=\"mb-2 text-xs font-thin truncate md:text-sm\">대한민국 거제통영</h2>\n");
      out.write("                        </div> <!-- /.portfolio-thumb -->\n");
      out.write("                    </div> <!-- /.portfolio-item -->\n");
      out.write("                       <div class=\"portfolio-item col-md-3 col-sm-7\">\n");
      out.write("                        <div class=\"portfolio-thumb\">\n");
      out.write("                            <img src=\"/resources/images/gallery/남원.jpg\" alt=\"\">\n");
      out.write("                            <h1 class=\"text-sm font-medium truncate md:text-2xl font-Montserrat\">NAMWON</h1>\n");
      out.write("<h2 class=\"mb-2 text-xs font-thin truncate md:text-sm\">대한민국 남원</h2>\n");
      out.write("                        </div> <!-- /.portfolio-thumb -->\n");
      out.write("                    </div> <!-- /.portfolio-item -->\n");
      out.write("                       <div class=\"portfolio-item col-md-3 col-sm-7\">\n");
      out.write("                        <div class=\"portfolio-thumb\">\n");
      out.write("                            <img src=\"/resources/images/gallery/전주.jpg\" alt=\"\">\n");
      out.write("                            <h1 class=\"text-sm font-medium truncate md:text-2xl font-Montserrat\">JEONJU</h1>\n");
      out.write("<h2 class=\"mb-2 text-xs font-thin truncate md:text-sm\">대한민국 전주</h2>\n");
      out.write("                        </div> <!-- /.portfolio-thumb -->\n");
      out.write("                    </div> <!-- /.portfolio-item -->\n");
      out.write("                       <div class=\"portfolio-item col-md-3 col-sm-7\">\n");
      out.write("                        <div class=\"portfolio-thumb\">\n");
      out.write("                            <img src=\"/resources/images/gallery/포항.jpg\" style=\"width:290px;\" alt=\"\">\n");
      out.write("                            <h1 class=\"text-sm font-medium truncate md:text-2xl font-Montserrat\">POHANG</h1>\n");
      out.write("<h2 class=\"mb-2 text-xs font-thin truncate md:text-sm\">대한민국 포항</h2>\n");
      out.write("                        </div> <!-- /.portfolio-thumb -->\n");
      out.write("                    </div> <!-- /.portfolio-item -->\n");
      out.write("                       <div class=\"portfolio-item col-md-3 col-sm-7\">\n");
      out.write("                        <div class=\"portfolio-thumb\">\n");
      out.write("                            <img src=\"/resources/images/gallery/인천.jpg\" alt=\"\">\n");
      out.write("                            <h1 class=\"text-sm font-medium truncate md:text-2xl font-Montserrat\">INCHEON</h1>\n");
      out.write("<h2 class=\"mb-2 text-xs font-thin truncate md:text-sm\">대한민국 인천</h2>\n");
      out.write("                        </div> <!-- /.portfolio-thumb -->\n");
      out.write("                    </div> <!-- /.portfolio-item -->\n");
      out.write("                       <div class=\"portfolio-item col-md-3 col-sm-7\">\n");
      out.write("                        <div class=\"portfolio-thumb\">\n");
      out.write("                            <img src=\"/resources/images/gallery/대전.jpg\" alt=\"\">\n");
      out.write("                            <h1 class=\"text-sm font-medium truncate md:text-2xl font-Montserrat\">DAEJEON</h1>\n");
      out.write("<h2 class=\"mb-2 text-xs font-thin truncate md:text-sm\">대한민국 대전</h2>\n");
      out.write("                        </div> <!-- /.portfolio-thumb -->\n");
      out.write("                    </div> <!-- /.portfolio-item -->\n");
      out.write("                       <div class=\"portfolio-item col-md-3 col-sm-7\">\n");
      out.write("                        <div class=\"portfolio-thumb\">\n");
      out.write("                            <img src=\"/resources/images/gallery/춘천.jpg\" alt=\"\">\n");
      out.write("                            <h1 class=\"text-sm font-medium truncate md:text-2xl font-Montserrat\">CHUNCHEON</h1>\n");
      out.write("<h2 class=\"mb-2 text-xs font-thin truncate md:text-sm\">대한민국 춘천</h2>\n");
      out.write("                        </div> <!-- /.portfolio-thumb -->\n");
      out.write("                    </div> <!-- /.portfolio-item -->\n");
      out.write("                       <div class=\"portfolio-item col-md-3 col-sm-7\">\n");
      out.write("                        <div class=\"portfolio-thumb\">\n");
      out.write("                            <img src=\"/resources/images/gallery/군산.jpg\" alt=\"\">\n");
      out.write("                            <h1 class=\"text-sm font-medium truncate md:text-2xl font-Montserrat\">GUNSAN</h1>\n");
      out.write("<h2 class=\"mb-2 text-xs font-thin truncate md:text-sm\">대한민국 군산</h2>\n");
      out.write("                        </div> <!-- /.portfolio-thumb -->\n");
      out.write("                    </div> <!-- /.portfolio-item -->\n");
      out.write("                                           <div class=\"portfolio-item col-md-3 col-sm-7\">\n");
      out.write("                        <div class=\"portfolio-thumb\">\n");
      out.write("                            <img src=\"/resources/images/gallery/목포.jpg\" alt=\"\">\n");
      out.write("                            <h1 class=\"text-sm font-medium truncate md:text-2xl font-Montserrat\">MOKPO</h1>\n");
      out.write("<h2 class=\"mb-2 text-xs font-thin truncate md:text-sm\">대한민국 목포</h2>\n");
      out.write("                        </div> <!-- /.portfolio-thumb -->\n");
      out.write("                    </div> <!-- /.portfolio-item -->\n");
      out.write("                                           <div class=\"portfolio-item col-md-3 col-sm-7\">\n");
      out.write("                        <div class=\"portfolio-thumb\">\n");
      out.write("                            <img src=\"/resources/images/gallery/안동.jpg\" alt=\"\">\n");
      out.write("                            <h1 class=\"text-sm font-medium truncate md:text-2xl font-Montserrat\">ANDONG</h1>\n");
      out.write("<h2 class=\"mb-2 text-xs font-thin truncate md:text-sm\">대한민국 안동</h2>\n");
      out.write("                        </div> <!-- /.portfolio-thumb -->\n");
      out.write("                    </div> <!-- /.portfolio-item -->\n");
      out.write("                                           <div class=\"portfolio-item col-md-3 col-sm-7\">\n");
      out.write("                        <div class=\"portfolio-thumb\">\n");
      out.write("                            <img src=\"/resources/images/gallery/울릉도.jpg\" alt=\"\">\n");
      out.write("                            <h1 class=\"text-sm font-medium truncate md:text-2xl font-Montserrat\">ULLEUNG</h1>\n");
      out.write("<h2 class=\"mb-2 text-xs font-thin truncate md:text-sm\">대한민국 울릉도</h2>\n");
      out.write("                        </div> <!-- /.portfolio-thumb -->\n");
      out.write("                    </div> <!-- /.portfolio-item -->\n");
      out.write("                                           <div class=\"portfolio-item col-md-3 col-sm-7\">\n");
      out.write("                        <div class=\"portfolio-thumb\">\n");
      out.write("                            <img src=\"/resources/images/gallery/제천.jpg\" alt=\"\">\n");
      out.write("                            <h1 class=\"text-sm font-medium truncate md:text-2xl font-Montserrat\">JECHEON</h1>\n");
      out.write("<h2 class=\"mb-2 text-xs font-thin truncate md:text-sm\">대한민국 제천</h2>\n");
      out.write("                        </div> <!-- /.portfolio-thumb -->\n");
      out.write("                    </div> <!-- /.portfolio-item -->\n");
      out.write("                                           <div class=\"portfolio-item col-md-3 col-sm-7\">\n");
      out.write("                        <div class=\"portfolio-thumb\">\n");
      out.write("                            <img src=\"/resources/images/gallery/가평.jpg\" alt=\"\">\n");
      out.write("                            <h1 class=\"text-sm font-medium truncate md:text-2xl font-Montserrat\">GAPYEONG</h1>\n");
      out.write("<h2 class=\"mb-2 text-xs font-thin truncate md:text-sm\">대한민국 가평</h2>\n");
      out.write("                        </div> <!-- /.portfolio-thumb -->\n");
      out.write("                    </div> <!-- /.portfolio-item -->\n");
      out.write("                                           <div class=\"portfolio-item col-md-3 col-sm-7\">\n");
      out.write("                        <div class=\"portfolio-thumb\">\n");
      out.write("                            <img src=\"/resources/images/gallery/수원.jpg\" alt=\"\">\n");
      out.write("                            <h1 class=\"text-sm font-medium truncate md:text-2xl font-Montserrat\">SUWON</h1>\n");
      out.write("<h2 class=\"mb-2 text-xs font-thin truncate md:text-sm\">대한민국 수원</h2>\n");
      out.write("                        </div> <!-- /.portfolio-thumb -->\n");
      out.write("                    </div> <!-- /.portfolio-item -->\n");
      out.write("                                           <div class=\"portfolio-item col-md-3 col-sm-7\">\n");
      out.write("                        <div class=\"portfolio-thumb\">\n");
      out.write("                            <img src=\"/resources/images/gallery/영월.jpg\" alt=\"\">\n");
      out.write("                            <h1 class=\"text-sm font-medium truncate md:text-2xl font-Montserrat\">YEONGWOL</h1>\n");
      out.write("<h2 class=\"mb-2 text-xs font-thin truncate md:text-sm\">대한민국 영월</h2>\n");
      out.write("                        </div> <!-- /.portfolio-thumb -->\n");
      out.write("                    </div> <!-- /.portfolio-item -->\n");
      out.write("                    \n");
      out.write("                </div> <!-- /.row -->\n");
      out.write("            </div> <!-- /.container -->\n");
      out.write("        </div> <!-- /#portfolio -->\n");
      out.write("        \n");
      out.write("                <div class=\"content-section\" id=\"services\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"heading-section col-md-12 text-center\">\n");
      out.write("                        <h2>Our Services</h2>\n");
      out.write("                        <p>We design mobile-first websites for you</p>\n");
      out.write("                    </div> <!-- /.heading-section -->\n");
      out.write("                </div> <!-- /.row -->\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col-md-3 col-sm-6\">\n");
      out.write("                        <div class=\"service-item\" id=\"service-1\">\n");
      out.write("                            <div class=\"service-icon\">\n");
      out.write("                                <i class=\"fa fa-file-code-o\"></i>\n");
      out.write("                            </div> <!-- /.service-icon -->\n");
      out.write("                            <div class=\"service-content\">\n");
      out.write("                                <div class=\"inner-service\">\n");
      out.write("                                   <h3>HTML5 Coding</h3>\n");
      out.write("                                   <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Enim, assumenda, eveniet, consectetur, ex doloribus veniam asperiores incidunt mollitia placeat aniet.</p> \n");
      out.write("                                </div>\n");
      out.write("                            </div> <!-- /.service-content -->\n");
      out.write("                        </div> <!-- /#service-1 -->\n");
      out.write("                    </div> <!-- /.col-md-3 -->\n");
      out.write("                    <div class=\"col-md-3 col-sm-6\">\n");
      out.write("                        <div class=\"service-item\" id=\"service-2\">\n");
      out.write("                            <div class=\"service-icon\">\n");
      out.write("                                <i class=\"fa fa-paper-plane-o\"></i>\n");
      out.write("                            </div> <!-- /.service-icon -->\n");
      out.write("                            <div class=\"service-content\">\n");
      out.write("                                <div class=\"inner-service\">\n");
      out.write("                                   <h3>Our Support</h3>\n");
      out.write("                                   <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Enim, assumenda, eveniet, consectetur, ex doloribus veniam asperiores incidunt mollitia placeat aniet.</p> \n");
      out.write("                                </div>\n");
      out.write("                            </div> <!-- /.service-content -->\n");
      out.write("                        </div> <!-- /#service-1 -->\n");
      out.write("                    </div> <!-- /.col-md-3 -->\n");
      out.write("                    <div class=\"col-md-3 col-sm-6\">\n");
      out.write("                        <div class=\"service-item\" id=\"service-3\">\n");
      out.write("                            <div class=\"service-icon\">\n");
      out.write("                                <i class=\"fa fa-institution\"></i>\n");
      out.write("                            </div> <!-- /.service-icon -->\n");
      out.write("                            <div class=\"service-content\">\n");
      out.write("                                <div class=\"inner-service\">\n");
      out.write("                                   <h3>Our Design</h3>\n");
      out.write("                                   <p>We make HTML CSS templates that are responsive for any screen size on any device. Feel free to download and use our templates without restrictions.</p> \n");
      out.write("                                </div>\n");
      out.write("                            </div> <!-- /.service-content -->\n");
      out.write("                        </div> <!-- /#service-1 -->\n");
      out.write("                    </div> <!-- /.col-md-3 -->\n");
      out.write("                    <div class=\"col-md-3 col-sm-6\">\n");
      out.write("                        <div class=\"service-item\" id=\"service-4\">\n");
      out.write("                            <div class=\"service-icon\">\n");
      out.write("                                <i class=\"fa fa-flask\"></i>\n");
      out.write("                            </div> <!-- /.service-icon -->\n");
      out.write("                            <div class=\"service-content\">\n");
      out.write("                                <div class=\"inner-service\">\n");
      out.write("                                   <h3>Go for mobile</h3>\n");
      out.write("                                   <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Enim, assumenda, eveniet, consectetur, ex doloribus veniam asperiores incidunt mollitia placeat aniet.</p> \n");
      out.write("                                </div>\n");
      out.write("                            </div> <!-- /.service-content -->\n");
      out.write("                        </div> <!-- /#service-1 -->\n");
      out.write("                    </div> <!-- /.col-md-3 -->\n");
      out.write("                </div> <!-- /.row -->\n");
      out.write("            </div> <!-- /.container -->\n");
      out.write("        </div> <!-- /#services -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("            \n");
      out.write("        <div id=\"footer\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col-md-8 col-xs-12 text-left\">\n");
      out.write("                        <span>Copyright &copy; 2014 Company Name</span>\n");
      out.write("                  </div> <!-- /.text-center -->\n");
      out.write("                    <div class=\"col-md-4 hidden-xs text-right\">\n");
      out.write("                        <a href=\"#top\" id=\"go-top\">Back to top</a>\n");
      out.write("                    </div> <!-- /.text-center -->\n");
      out.write("                </div> <!-- /.row -->\n");
      out.write("            </div> <!-- /.container -->\n");
      out.write("        </div> <!-- /#footer -->\n");
      out.write("        \n");
      out.write("        <script src=\"/resources/js/vendor/jquery-1.11.0.min.js\"></script>\n");
      out.write("        <script>window.jQuery || document.write('<script src=\"/resources/js/vendor/jquery-1.11.0.min.js\"><\\/script>')</script>\n");
      out.write("        <script src=\"/resources/js/bootstrap.js\"></script>\n");
      out.write("        <script src=\"/resources/js/plugins.js\"></script>\n");
      out.write("        <script src=\"/resources/js/main.js\"></script>\n");
      out.write("  \n");
      out.write("    </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_sec_005fauthorize_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f0 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f0_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f0.setParent(null);
      // /WEB-INF/views/includes/header1.jsp(42,40) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f0.setAccess("isAnonymous()");
      int _jspx_eval_sec_005fauthorize_005f0 = _jspx_th_sec_005fauthorize_005f0.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write(" <!-- 로그인 안했을 때 표시 -->\n");
        out.write("                                        <li><a href=\"/customLogin\">로그인</a></li>\n");
        out.write("                                        ");
      }
      if (_jspx_th_sec_005fauthorize_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f0);
      _jspx_th_sec_005fauthorize_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f0, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthorize_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f1 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f1_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f1.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f1.setParent(null);
      // /WEB-INF/views/includes/header1.jsp(45,40) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f1.setAccess("isAuthenticated()");
      int _jspx_eval_sec_005fauthorize_005f1 = _jspx_th_sec_005fauthorize_005f1.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write(" <!--  로그인 하였을 때 표시 -->\n");
        out.write("                                        <li><a href=\"/customLogout\">로그아웃</a></li>\n");
        out.write("                                        ");
      }
      if (_jspx_th_sec_005fauthorize_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f1);
      _jspx_th_sec_005fauthorize_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f1, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f1_reused);
    }
    return false;
  }
}
