/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-04-16 07:37:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class use_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/java/Spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Odga/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1712112365428L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!doctype html>\n");
      out.write("<html class=\"no-js\" lang=\"zxx\">\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"utf-8\">\n");
      out.write("       <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"assets/img/favicon.ico\">\n");
      out.write("		  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\" />\n");
      out.write("		  <title>\n");
      out.write("		    Odga.com\n");
      out.write("		  </title>\n");
      out.write("        <meta name=\"description\" content=\"\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("        <link rel=\"manifest\" href=\"site.webmanifest\">\n");
      out.write("		<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"assets/img/favicon.ico\">\n");
      out.write("		<!-- CSS here -->\n");
      out.write("            <link rel=\"stylesheet\" href=\"assets/css/bootstrap.min.css\">\n");
      out.write("            <link rel=\"stylesheet\" href=\"assets/css/owl.carousel.min.css\">\n");
      out.write("            <link rel=\"stylesheet\" href=\"assets/css/slicknav.css\">\n");
      out.write("            <link rel=\"stylesheet\" href=\"assets/css/flaticon.css\">\n");
      out.write("            <link rel=\"stylesheet\" href=\"assets/css/animate.min.css\">\n");
      out.write("            <link rel=\"stylesheet\" href=\"assets/css/magnific-popup.css\">\n");
      out.write("            <link rel=\"stylesheet\" href=\"assets/css/fontawesome-all.min.css\">\n");
      out.write("            <link rel=\"stylesheet\" href=\"assets/css/themify-icons.css\">\n");
      out.write("            <link rel=\"stylesheet\" href=\"assets/css/slick.css\">\n");
      out.write("            <link rel=\"stylesheet\" href=\"assets/css/nice-select.css\">\n");
      out.write("            <link rel=\"stylesheet\" href=\"assets/css/style.css\">\n");
      out.write("            <link rel=\"stylesheet\" href=\"assets/css/card.css\">\n");
      out.write("            <link rel=\"stylesheet\" href=\"assets/css/tutorial.css\">\n");
      out.write("   </head>\n");
      out.write("<style>\n");
      out.write(".swal-button--확인 {background-color:#ff3d1c}.swal-button--확인:not([disabled]):hover {background-color:#ff5235}.swal-button--확인:active {background-color:#ff5235}\n");
      out.write("</style>\n");
      out.write("<body>\n");
      out.write("	<!-- Preloader Start -->\n");
      out.write("    <div id=\"preloader-active\">\n");
      out.write("        <div class=\"preloader d-flex align-items-center justify-content-center\">\n");
      out.write("            <div class=\"preloader-inner position-relative\">\n");
      out.write("                <div class=\"preloader-circle\"></div>\n");
      out.write("                <div class=\"preloader-img pere-text\">\n");
      out.write("                    <img src=\"assets/img/logo/loder1_d.jpg\" alt=\"\">\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("<header>\n");
      out.write("        <!-- Header Start -->\n");
      out.write("       <div class=\"header-area header-transparent\">\n");
      out.write("            <div class=\"main-header\">\n");
      out.write("               <div class=\"header-bottom  header-sticky\">\n");
      out.write("                    <div class=\"container-fluid\">\n");
      out.write("                        <div class=\"row align-items-center\">\n");
      out.write("                            <!-- Logo -->\n");
      out.write("                            <div style=\"width: 10%;min-width: 9rem;\">\n");
      out.write("                                <a href=\"index.do\"><img src=\"assets/img/logo/logo_b.png\" alt=\"\" style=\"max-width: 100%;\"></a>\n");
      out.write("                            </div>\n");
      out.write("                            <!-- Main-menu -->\n");
      out.write("                              <div style=\"width: 84%;\" class=\"main-menu f-right d-none d-lg-block\" align=\"right\">\n");
      out.write("                               <nav>\n");
      out.write("                           <ul id=\"navigation\" style=\"width: 100%;float: left;\">\n");
      out.write("                              <ul style=\"float: left;width: 80%;\">\n");
      out.write("                                    <li><a href=\"listing.do\">국내여행지</a></li>\n");
      out.write("                                    <li><a href=\"review.do\">커뮤니티</a>\n");
      out.write("                                       <ul class=\"submenu\" style=\"text-align: left;\">\n");
      out.write("                                          <li><a href=\"review.do\">여행후기</a></li>\n");
      out.write("                                          <li><a onclick=\"goSupport()\" style =\"cursor: pointer;\">문의하기</a></li>\n");
      out.write("                                       </ul>\n");
      out.write("                                    </li>\n");
      out.write("                                    <li><a href=\"use.do\">이용방법</a></li>\n");
      out.write("                                    <li><a href=\"https://www.agoda.com/\">호텔예약</a></li>\n");
      out.write("                                    ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("                                  \n");
      out.write("                                    ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                                    <li class=\"add-list\" style=\"display: inline flow-root list-item;\">\n");
      out.write("                                       <a onclick=\"goPlanner()\" style =\"cursor: pointer;\"><i class=\"ti-plus\"></i>나의 여행 만들기</a>\n");
      out.write("                                    </li>\n");
      out.write("                              </ul>\n");
      out.write("                              <ul style=\"float: left;width: 20%;padding-top: 23px;\" align=\"left\">   \n");
      out.write("                                 <li class=\"login img-wrapper\" style=\"width: 75%;padding: 1%;text-align: center;float:left;\">                          \n");
      out.write("                                             ");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                                          </li>\n");
      out.write("                                          ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("                                    \n");
      out.write("                                      </ul>\n");
      out.write("                                      \n");
      out.write("		                           </ul>\n");
      out.write("		                        </nav>\n");
      out.write("		                     </div>\n");
      out.write("                            <!-- Mobile Menu -->\n");
      out.write("                            <div class=\"col-12\">\n");
      out.write("                                <div class=\"mobile_menu d-block d-lg-none\"></div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("               </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- Header End -->\n");
      out.write("    </header>\n");
      out.write("    <main>\n");
      out.write("\n");
      out.write("        <!-- Hero Start-->\n");
      out.write("         <div class=\"hero-area2  slider-height2 hero-overly2 d-flex align-items-center\" style=\"background-image: url(assets/img/myPlanImg/12.jpg);\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col-xl-12\">\n");
      out.write("                        <div class=\"hero-cap text-center pt-50\">\n");
      out.write("                            <h2>이용 방법</h2>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!--Hero End -->\n");
      out.write("        <!--\n");
      out.write("        <!-- Categories Area Start -->\n");
      out.write("        <div class=\"categories-area section-padding30\">\n");
      out.write("            <div class=\"container2\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col-lg-12\">\n");
      out.write("                        <!-- Section Tittle -->\n");
      out.write("                        <div class=\"section-tittle text-center mb-80\">\n");
      out.write("                            <span>ODGA</span>\n");
      out.write("                            <h2>여행 동선을 쉽게 확인하기</h2>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("		        <!-- Services Area Start -->\n");
      out.write("		        <ul class=\"card-list\">\n");
      out.write("					<li class=\"card\">\n");
      out.write("	                  <a class=\"card-image\" onclick=\"goListing()\" target=\"_blank\" style=\"background-image: assets/img/use/p1.jpg;\" data-image-full=\"assets/img/use/p1.jpg\">\n");
      out.write("	                     <img src=\"assets/img/use/p1.jpg\" alt=\"Psychopomp\" />\n");
      out.write("	                  </a>\n");
      out.write("	                  <a class=\"card-description\" onclick=\"goListing()\" target=\"_blank\">\n");
      out.write("	                     <hh2>1. 지역 찾기</hh2>\n");
      out.write("	                     <p>리스트에서 여행지를 찾아서 선택 해보세요.</p>\n");
      out.write("	                  </a>\n");
      out.write("	               </li>\n");
      out.write("					\n");
      out.write("					<li class=\"card\">\n");
      out.write("						<a class=\"card-image\" onclick=\"goPlanner()\" style=\"background-image: assets/img/use/p3.jpg;cursor: pointer;\" data-image-full=\"assets/img/use/p3.jpg\">\n");
      out.write("							<img src=\"assets/img/use/p3.jpg\" alt=\"The Beautiful Game\"/>\n");
      out.write("						</a>\n");
      out.write("						<a class=\"card-description\" onclick=\"goPlanner()\" style=\"cursor: pointer;\" target=\"_blank\">\n");
      out.write("							<hh2>2. 플래너 작성</hh2>\n");
      out.write("							<p>플래너를 통해 일정을 계획해보세요.</p>\n");
      out.write("						</a>\n");
      out.write("					</li>\n");
      out.write("					\n");
      out.write("					<li class=\"card\">\n");
      out.write("						<a class=\"card-image\" onclick=\"goMypage()\" target=\"_blank\" style=\"background-image: assets/img/use/p2.jpg;cursor: pointer;\" data-image-full=\"assets/img/use/p2.jpg\">\n");
      out.write("							<img src=\"assets/img/use/p2.jpg\" alt=\"let's go\" style=\"height: 357px;\"/>\n");
      out.write("						</a>\n");
      out.write("						<a class=\"card-description\" onclick=\"goMypage()\" style=\"cursor: pointer;\" target=\"_blank\">\n");
      out.write("							<hh2>3. 마이페이지에서 확인</hh2>\n");
      out.write("							<p>작성한 플래너를 확인 해보세요.</p>\n");
      out.write("						</a>\n");
      out.write("					</li> \n");
      out.write("					\n");
      out.write("					<li class=\"card\">\n");
      out.write("						<a class=\"card-image\" href=\"https://www.skyscanner.co.kr/\" target=\"_blank\" style=\"background-image: assets/img/use/p4.jpg;\" data-image-full=\"assets/img/use/p4.jpg\">\n");
      out.write("							<img src=\"assets/img/use/p4.jpg\" alt=\"Jane Doe\" />\n");
      out.write("						</a>\n");
      out.write("						<a class=\"card-description\" href=\"\" target=\"_blank\">\n");
      out.write("							<hh2>4. 여행하기</hh2>\n");
      out.write("							<p>일정이 정해지셨다면 떠나보세요!</p>\n");
      out.write("						</a>\n");
      out.write("					</li>\n");
      out.write("				</ul>\n");
      out.write("		        <!-- Services Area End -->\n");
      out.write("		        <!-- Popular Locations Start -->\n");
      out.write("		         <div style=\"display:flex;justify-content:center; margin: 15;\">	 \n");
      out.write("		        	 <div class=\"container1\" >\n");
      out.write("				  <div class=\"image-viewer\">\n");
      out.write("				    <div class=\"main-image\">\n");
      out.write("				      <img src=\"assets/img/use/1.jpg\" style=\"min-height: 113%;max-width: 88%;border: 0.4rem solid #010e21;\"/>\n");
      out.write("				    </div>\n");
      out.write("				    </div>\n");
      out.write("				  </div>\n");
      out.write("				  <div class=\"detail\">\n");
      out.write("				    <h1 class=\"detail-name\">Step1 여행지찾기🔎</h1>\n");
      out.write("				    <p class=\"detail-short-description\"> \n");
      out.write("				     여행지 리스트에서 검색을 통해 알아보세요.\n");
      out.write("				    </p>\n");
      out.write("				  </div>\n");
      out.write("				</div>\n");
      out.write("				<div style=\"display:flex;justify-content:center; margin: 15;\">	 \n");
      out.write("		        	 <div class=\"container1\" >\n");
      out.write("				  <div class=\"image-viewer\">\n");
      out.write("				    <div class=\"main-image\">\n");
      out.write("				      <img src=\"assets/img/use/2.jpg\" style=\"min-height: 113%;max-width: 88%;border: 0.4rem solid #010e21;\"/>\n");
      out.write("				    </div>\n");
      out.write("				    </div>\n");
      out.write("				  </div>\n");
      out.write("				  <div class=\"detail\">\n");
      out.write("				    <h1 class=\"detail-name\">Step2 일정만들기📃</h1>\n");
      out.write("				    <p class=\"detail-short-description\"> \n");
      out.write("				      가고싶은 장소 또는 관심있는 장소 이신가요? 일정에 담아 계획을 세워보세요.\n");
      out.write("				    </p>\n");
      out.write("				  </div>\n");
      out.write("				</div>\n");
      out.write("				<div style=\"display:flex;justify-content:center; margin: 15;\">	 \n");
      out.write("		        	 <div class=\"container1\" >\n");
      out.write("				  <div class=\"image-viewer\">\n");
      out.write("				    <div class=\"main-image\">\n");
      out.write("				      <img src=\"assets/img/use/3.jpg\" style=\"min-height: 113%;max-width: 88%;border: 0.4rem solid #010e21;\"/>\n");
      out.write("				    </div>\n");
      out.write("				    </div>\n");
      out.write("				  </div>\n");
      out.write("				  <div class=\"detail\">\n");
      out.write("				    <h1 class=\"detail-name\">Step3 플래너 작성✏</h1>\n");
      out.write("				    <p class=\"detail-short-description\"> \n");
      out.write("				       일정에 담은 장소들을 지도에서 확인해보세요 인근의 맛집 명소들을 한눈에 확인 할 수 있습니다.\n");
      out.write("				    </p>\n");
      out.write("				  </div>\n");
      out.write("				</div> \n");
      out.write("				<div style=\"display:flex;justify-content:center; margin: 15;\">	 \n");
      out.write("		        	 <div class=\"container1\" >\n");
      out.write("				  <div class=\"image-viewer\">\n");
      out.write("				    <div class=\"main-image\">\n");
      out.write("				      <img src=\"assets/img/use/4.jpg\" style=\"border: 0.4rem solid #010e21;max-height:  90%;min-width: 100%;\"/>\n");
      out.write("				    </div>\n");
      out.write("				    </div>\n");
      out.write("				  </div>\n");
      out.write("				  <div class=\"detail\" style=\"padding-top: 4.6%;padding-left: 2%;\">\n");
      out.write("				    <h1 class=\"detail-name\">Step4 여행하기✈</h1>\n");
      out.write("				    <p class=\"detail-short-description\"> \n");
      out.write("				      완성된 일정을 친구들과 공유해보세요! 길찾기와 메모만 잘 활용해도 여행 준비 끝!\n");
      out.write("				    </p>\n");
      out.write("				  </div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		\n");
      out.write("		        <!-- Popular Locations End -->\n");
      out.write("\n");
      out.write("    </main>\n");
      out.write("   	<!-- Footer Start-->\n");
      out.write("	<footer>\n");
      out.write("	<div class=\"footer-area\">\n");
      out.write("		<div class=\"container\">\n");
      out.write("			<div class=\"footer-top footer-padding\">\n");
      out.write("				<div class=\"row justify-content-between\">\n");
      out.write("					<div class=\"col-xl-3 col-lg-4 col-md-4 col-sm-6\">\n");
      out.write("						<div class=\"single-footer-caption mb-50\">\n");
      out.write("							<div class=\"col-xl-2 col-lg-2 col-md-1\">\n");
      out.write("							<!-- Logo -->\n");
      out.write("                               <div class=\"logo\">\n");
      out.write("                                 <a href=\"index.html\"><img src=\"assets/img/logo/logo_b.png\" alt=\"\" style=\"max-width: 170px;\"></a>\n");
      out.write("                               </div>\n");
      out.write("                              </div>\n");
      out.write("						 </div>\n");
      out.write("						</div>\n");
      out.write("					<div class=\"col-xl-2 col-lg-2 col-md-4 col-sm-6\">\n");
      out.write("						<div class=\"single-footer-caption mb-50\">\n");
      out.write("							<div class=\"footer-tittle\">\n");
      out.write("								<h4>Administrator</h4>\n");
      out.write("								<ul>\n");
      out.write("									<li><a href=\"https://github.com/dragongit94\">이민용</a></li>\n");
      out.write("									<li><a href=\"https://github.com/yumgit23\">허유민</a></li>\n");
      out.write("									<li><a href=\"https://github.com/suadeomgit\">권성환</a></li>\n");
      out.write("									<li><a href=\"https://github.com/lzhxxn\">이지훈</a></li>\n");
      out.write("									<li><a href=\"https://github.com/DobbyisFree1\">박종범</a></li>\n");
      out.write("								</ul>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"col-xl-2 col-lg-3 col-md-4 col-sm-6\">\n");
      out.write("						<div class=\"single-footer-caption mb-50\">\n");
      out.write("							<div class=\"footer-tittle\">\n");
      out.write("								<h4>Quick Links</h4>\n");
      out.write("								<ul>\n");
      out.write("									");
      if (_jspx_meth_c_005fchoose_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("									<li><a href=\"listing.do\">국내여행지</a></li>\n");
      out.write("									<li><a href=\"use.do\">이용방법</a>\n");
      out.write("									<li><a onclick=\"goPlanner()\" style=\"cursor:pointer;\">나의 여행 만들기</a></li>\n");
      out.write("									<li><a onclick=\"goSupport()\" style=\"cursor:pointer;\">문의하기</a></li>\n");
      out.write("								</ul>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"col-xl-3 col-lg-3 col-md-4 col-sm-6\">\n");
      out.write("						<div class=\"single-footer-caption mb-50\">\n");
      out.write("							<div class=\"footer-tittle\">\n");
      out.write("								<h4>Contact with Us</h4>\n");
      out.write("								<ul>\n");
      out.write("									<li><span class=\"la la-home\"></span> 서울 마포구 백범로 23 3층</li>\n");
      out.write("									<li><span class=\"la la-headphones\"></span>+ 81 02 707 1480</li>\n");
      out.write("									<li><span class=\"la la-envelope-o\"></span>odgacom@naver.com</li>\n");
      out.write("								</ul>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"footer-bottom\">\n");
      out.write("				<div class=\"row d-flex justify-content-between align-items-center\">\n");
      out.write("					<div class=\"col-xl-9 col-lg-8\">\n");
      out.write("						<div class=\"footer-copy-right\">\n");
      out.write("							<p>\n");
      out.write("								&copy; Copyright \n");
      out.write("								<script>\n");
      out.write("									document\n");
      out.write("											.write(new Date().getFullYear());\n");
      out.write("								</script>\n");
      out.write("								<b>Odga.com</b> Made with\n");
      out.write("								<i class=\"fa fa-heart\" aria-hidden=\"true\"></i>\n");
      out.write("								<a href=\"https://github.com/lzhxxn\" target=\"_blank\">JH</a>\n");
      out.write("								<a href=\"https://github.com/dragongit94\" target=\"_blank\">MY</a>\n");
      out.write("								<a href=\"https://github.com/yumgit23\" target=\"_blank\">YM</a>\n");
      out.write("								<a href=\"https://github.com/DobbyisFree1\" target=\"_blank\">JB</a>\n");
      out.write("								<a href=\"https://github.com/suadeomgit\" target=\"_blank\">SH</a>\n");
      out.write("								<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\n");
      out.write("							</p>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"col-xl-3 col-lg-4\">\n");
      out.write("						<!-- Footer Social -->\n");
      out.write("						<div class=\"footer-social f-right\">\n");
      out.write("							<a href=\"https://www.instagram.com/odga__com\"><i class=\"fas fa-globe\"></i></a> \n");
      out.write("							<a href=\"https://www.instagram.com/odga__com\"><i class=\"fab fa-instagram\"></i></a>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	</footer>\n");
      out.write("	<!-- Footer End-->\n");
      out.write("    <!-- Scroll Up -->\n");
      out.write("    <div id=\"back-top\" >\n");
      out.write("        <a title=\"Go to Top\" href=\"#\"> <i class=\"fas fa-level-up-alt\"></i></a>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("<script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("function salert(){\n");
      out.write("	swal({\n");
      out.write("		text: \"로그인 후 이용 가능합니다.\",\n");
      out.write("		buttons:{\"확인\":true,cancel:\"취소\"},\n");
      out.write("		}).then((value) => {\n");
      out.write("			if(value){\n");
      out.write("				location.href = \"login.do\";\n");
      out.write("			}\n");
      out.write("		});\n");
      out.write("}\n");
      out.write("function goPlanner(){\n");
      out.write("	if(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty LOGINUSER}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("){\n");
      out.write("			salert();\n");
      out.write("	}else{\n");
      out.write("		location.href = \"planner?m_id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${LOGINUSER.m_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\n");
      out.write("	}\n");
      out.write("}\n");
      out.write("function goSupport(){\n");
      out.write("	if(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty LOGINUSER}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("){\n");
      out.write("		salert();\n");
      out.write("	}else{\n");
      out.write("		location.href = \"support.do?m_id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${LOGINUSER.m_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\n");
      out.write("	}\n");
      out.write("}\n");
      out.write("function goMypage(){\n");
      out.write("	if(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${LOGINUSER.m_verify eq 9}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("){\n");
      out.write("		location.href = \"dashboard.do?m_id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${LOGINUSER.m_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\n");
      out.write("	}else{\n");
      out.write("		location.href = \"member.do?m_id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${LOGINUSER.m_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\n");
      out.write("	}\n");
      out.write("}\n");
      out.write("function goListing(){\n");
      out.write("    location.href = \"listing.do\";\n");
      out.write("}\n");
      out.write("function logout(){\n");
      out.write("    swal({\n");
      out.write("        text: \"로그아웃 하시겠습니까 ?\",\n");
      out.write("        buttons:{\"확인\":true,cancel:\"취소\"},\n");
      out.write("        }).then((value) => {\n");
      out.write("           if(value){\n");
      out.write("               swal({\n");
      out.write("                    text: \"로그아웃 되었습니다.\",\n");
      out.write("                    buttons:{\"확인\":true},\n");
      out.write("                    }).then((value) => {\n");
      out.write("                       if(value){\n");
      out.write("                          location.href=\"logout.do\";\n");
      out.write("                       }else{\n");
      out.write("                          location.href=\"logout.do\";\n");
      out.write("                       }\n");
      out.write("                    });            \n");
      out.write("           }\n");
      out.write("        });  \n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("    <!-- JS here -->\n");
      out.write("		<!-- All JS Custom Plugins Link Here here -->\n");
      out.write("        <script src=\"./assets/js/vendor/modernizr-3.5.0.min.js\"></script>\n");
      out.write("		<!-- Jquery, Popper, Bootstrap -->\n");
      out.write("		<script src=\"./assets/js/vendor/jquery-1.12.4.min.js\"></script>\n");
      out.write("        <script src=\"./assets/js/popper.min.js\"></script>\n");
      out.write("        <script src=\"./assets/js/bootstrap.min.js\"></script>\n");
      out.write("	    <!-- Jquery Mobile Menu -->\n");
      out.write("        <script src=\"./assets/js/jquery.slicknav.min.js\"></script>\n");
      out.write("\n");
      out.write("		<!-- Jquery Slick , Owl-Carousel Plugins -->\n");
      out.write("        <script src=\"./assets/js/owl.carousel.min.js\"></script>\n");
      out.write("        <script src=\"./assets/js/slick.min.js\"></script>\n");
      out.write("		<!-- One Page, Animated-HeadLin -->\n");
      out.write("        <script src=\"./assets/js/wow.min.js\"></script>\n");
      out.write("		<script src=\"./assets/js/animated.headline.js\"></script>\n");
      out.write("        <script src=\"./assets/js/jquery.magnific-popup.js\"></script>\n");
      out.write("\n");
      out.write("		<!-- Nice-select, sticky -->\n");
      out.write("        <script src=\"./assets/js/jquery.nice-select.min.js\"></script>\n");
      out.write("		<script src=\"./assets/js/jquery.sticky.js\"></script>\n");
      out.write("        \n");
      out.write("        <!-- contact js -->\n");
      out.write("        <script src=\"./assets/js/contact.js\"></script>\n");
      out.write("        <script src=\"./assets/js/jquery.form.js\"></script>\n");
      out.write("        <script src=\"./assets/js/jquery.validate.min.js\"></script>\n");
      out.write("        <script src=\"./assets/js/mail-script.js\"></script>\n");
      out.write("        <script src=\"./assets/js/jquery.ajaxchimp.min.js\"></script>\n");
      out.write("        \n");
      out.write("		<!-- Jquery Plugins, main Jquery -->	\n");
      out.write("        <script src=\"./assets/js/plugins.js\"></script>\n");
      out.write("        <script src=\"./assets/js/main.js\"></script>\n");
      out.write("        <script>\n");
      out.write("	     // wait for the entire page to finish loading\n");
      out.write("	     window.addEventListener('load', function() {\n");
      out.write("	     	\n");
      out.write("	     	// setTimeout to simulate the delay from a real page load\n");
      out.write("	     	setTimeout(lazyLoad, 1000);\n");
      out.write("	     	\n");
      out.write("	     });\n");
      out.write("		// 4카드\n");
      out.write("	     function lazyLoad() {\n");
      out.write("	     	var card_images = document.querySelectorAll('.card-image');\n");
      out.write("	     	\n");
      out.write("	     	// loop over each card image\n");
      out.write("	     	card_images.forEach(function(card_image) {\n");
      out.write("	     		var image_url = card_image.getAttribute('data-image-full');\n");
      out.write("	     		var content_image = card_image.querySelector('img');\n");
      out.write("	     		\n");
      out.write("	     		// change the src of the content image to load the new high res photo\n");
      out.write("	     		content_image.src = image_url;\n");
      out.write("	     		\n");
      out.write("	     		// listen for load event when the new photo is finished loading\n");
      out.write("	     		content_image.addEventListener('load', function() {\n");
      out.write("	     			// swap out the visible background image with the new fully downloaded photo\n");
      out.write("	     			card_image.style.backgroundImage = 'url(' + image_url + ')';\n");
      out.write("	     			// add a class to remove the blur filter to smoothly transition the image change\n");
      out.write("	     			card_image.className = card_image.className + ' is-loaded';\n");
      out.write("	     		});\n");
      out.write("	     		\n");
      out.write("	     	});\n");
      out.write("	     	\n");
      out.write("	     }\n");
      out.write("	     //튜토리얼\n");
      out.write("	     class ImageViewer {\n");
      out.write("	    	  constructor(selector) {\n");
      out.write("	    	    this.selector = selector;\n");
      out.write("	    	    $(this.secondaryImages).click(() => this.setMainImage(event));\n");
      out.write("	    	    $(this.mainImage).click(() => this.showLightbox(event));\n");
      out.write("	    	    $(this.lightboxClose).click(() => this.hideLightbox(event));\n");
      out.write("	    	  }\n");
      out.write("	    	  \n");
      out.write("	    	  get secondaryImageSelector() {\n");
      out.write("	    	    return '.secondary-image';\n");
      out.write("	    	  }\n");
      out.write("	    	  \n");
      out.write("	    	  get mainImageSelector() {\n");
      out.write("	    	    return '.main-image';\n");
      out.write("	    	  }\n");
      out.write("	    	  \n");
      out.write("	    	  get lightboxImageSelector() {\n");
      out.write("	    	    return '.lightbox';\n");
      out.write("	    	  }\n");
      out.write("	    	  \n");
      out.write("	    	  get lightboxClose() {\n");
      out.write("	    	    return '.lightbox-controls-close';\n");
      out.write("	    	  }\n");
      out.write("	    	  \n");
      out.write("	    	  get secondaryImages() {\n");
      out.write("	    	    var secondaryImages = $(this.selector).find(this.secondaryImageSelector).find('img')\n");
      out.write("	    	    return secondaryImages;\n");
      out.write("	    	  }\n");
      out.write("	    	  \n");
      out.write("	    	  get mainImage() {\n");
      out.write("	    	    var mainImage = $(this.selector).find(this.mainImageSelector);\n");
      out.write("	    	    return mainImage;\n");
      out.write("	    	  }\n");
      out.write("	    	  \n");
      out.write("	    	  get lightboxImage() {\n");
      out.write("	    	    var lightboxImage = $(this.lightboxImageSelector);\n");
      out.write("	    	    return lightboxImage;\n");
      out.write("	    	  }\n");
      out.write("	    	  \n");
      out.write("	    	  setLightboxImage(event){\n");
      out.write("	    	    var src = this.getEventSrc(event);\n");
      out.write("	    	    this.setSrc(this.lightboxImage, src);\n");
      out.write("	    	  }\n");
      out.write("	    	  \n");
      out.write("	    	  setMainImage(event){\n");
      out.write("	    	    var src = this.getEventSrc(event);\n");
      out.write("	    	    this.setSrc(this.mainImage, src);\n");
      out.write("	    	  }\n");
      out.write("	    	  \n");
      out.write("	    	  getSrc(node){\n");
      out.write("	    	    var image = $(node).find('img');\n");
      out.write("	    	  }\n");
      out.write("	    	  \n");
      out.write("	    	  setSrc(node, src){\n");
      out.write("	    	    var image = $(node).find('img')[0];\n");
      out.write("	    	    image.src = src;\n");
      out.write("	    	  }\n");
      out.write("	    	  \n");
      out.write("	    	  getEventSrc(event){\n");
      out.write("	    	    return event.target.src;\n");
      out.write("	    	  }\n");
      out.write("	    	  \n");
      out.write("	    	  showLightbox(event){\n");
      out.write("	    	    this.setLightboxImage(event);\n");
      out.write("	    	    $(this.lightboxImageSelector).addClass('show');\n");
      out.write("	    	  }\n");
      out.write("	    	  \n");
      out.write("	    	  hideLightbox(){\n");
      out.write("	    	    $(this.lightboxImageSelector).removeClass('show');\n");
      out.write("	    	  }\n");
      out.write("	    	}\n");
      out.write("\n");
      out.write("	    	new ImageViewer('.image-viewer');\n");
      out.write("        </script>\n");
      out.write("\n");
      out.write("    </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/use.jsp(72,36) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${LOGINUSER.m_verify eq 0}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                                    	<li><a href=\"member.do\">마이페이지</a></li>\n");
          out.write("                                    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/use.jsp(75,36) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${LOGINUSER.m_verify eq 9}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                                    	<li><a href=\"dashboard.do\">관리자페이지</a></li>\n");
          out.write("                                    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                                                   ");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("                                                   ");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("                                             ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/use.jsp(85,51) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty LOGINUSER}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                                                      <a href=\"login.do\" style=\"padding: inherit;font-size: 80%;\">\n");
          out.write("                                                         <div style=\"float: left;font-size: 200%;margin-top: 7px;margin-left: 45px;\">\n");
          out.write("                                                            <i class=\"ti-user\"></i>\n");
          out.write("                                                         </div>\n");
          out.write("                                                         <div style=\"width: 39%;float: left;margin-top: -22px;\">\n");
          out.write("                                                            </br>로그인</br>&</br>회원가입\n");
          out.write("                                                         </div>\n");
          out.write("                                                      </a>\n");
          out.write("                                                   ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                                                      ");
          if (_jspx_meth_c_005fchoose_005f1(_jspx_th_c_005fotherwise_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("                                                   ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fotherwise_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f1 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f1_reused = false;
    try {
      _jspx_th_c_005fchoose_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fotherwise_005f0);
      int _jspx_eval_c_005fchoose_005f1 = _jspx_th_c_005fchoose_005f1.doStartTag();
      if (_jspx_eval_c_005fchoose_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                                                         ");
          if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("                                           \n");
          out.write("                                                         ");
          if (_jspx_meth_c_005fotherwise_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("                                                       ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f1);
      _jspx_th_c_005fchoose_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f1_reused = false;
    try {
      _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      // /WEB-INF/views/use.jsp(97,57) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${LOGINUSER.m_verify eq 0}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
      if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                                                            <a onclick=\"logout()\" style=\"padding: inherit;font-size: 100%; margin-top: 7%;cursor:pointer;\"><i class=\"ti-user\"></i>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${LOGINUSER.m_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("님 로그아웃</a>                                                             										          \n");
          out.write("                                                          <!--   <li style=\"width: 100%;padding: 0%;float: left;text-align: center;\"><a href=\"member.do\" style=\"padding: inherit;font-size: 80%;\"><i class=\"ti-user\"></i> 마이페이지</a></li> -->\n");
          out.write("                                                         ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      _jspx_th_c_005fwhen_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f1 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f1_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      int _jspx_eval_c_005fotherwise_005f1 = _jspx_th_c_005fotherwise_005f1.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                                                             <a onclick=\"logout()\" style=\"padding: inherit;font-size: 100%; margin-top: 7%;cursor:pointer;\"><i class=\"ti-user\"></i>관리자님 로그아웃</a>\n");
          out.write("                                                           <!--  <li style=\"width: 100%;padding: 0%;float: left;text-align: center;\"><a href=\"dashboard.do\" style=\"padding: inherit;font-size: 80%;\"><i class=\"ti-user\"></i> 관리자페이지</a></li> -->\n");
          out.write("                                                         ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f1);
      _jspx_th_c_005fotherwise_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/use.jsp(109,42) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty LOGINUSER}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("	 										<li class=\"img-wrapper\" style=\"float: right;width: 25%;\">   \n");
          out.write("	                                      	 <div class=\"main-menu f-right d-none d-lg-block\"><img class=\"img-fluid\" onclick=\"goMypage()\" src=\"assets/img/profile/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${LOGINUSER.m_fname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" alt=\"\" style=\"cursor: pointer;min-height:60px;width: 60px;border-radius: 50%;max-width: 100%;border: 3px solid white;\">\n");
          out.write("			                                    </div>\n");
          out.write("			                           		</li> \n");
          out.write("			                           		");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f2 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f2_reused = false;
    try {
      _jspx_th_c_005fchoose_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f2.setParent(null);
      int _jspx_eval_c_005fchoose_005f2 = _jspx_th_c_005fchoose_005f2.doStartTag();
      if (_jspx_eval_c_005fchoose_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("		                                 ");
          if (_jspx_meth_c_005fwhen_005f2(_jspx_th_c_005fchoose_005f2, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("		                                 ");
          if (_jspx_meth_c_005fotherwise_005f2(_jspx_th_c_005fchoose_005f2, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("		                            ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f2);
      _jspx_th_c_005fchoose_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f2 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f2_reused = false;
    try {
      _jspx_th_c_005fwhen_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f2);
      // /WEB-INF/views/use.jsp(306,35) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ empty LOGINUSER }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f2 = _jspx_th_c_005fwhen_005f2.doStartTag();
      if (_jspx_eval_c_005fwhen_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("		                                    <li><a href=\"login.do\">로그인 & 회원가입</a></li>\n");
          out.write("		                                 ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f2);
      _jspx_th_c_005fwhen_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f2 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f2_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f2);
      int _jspx_eval_c_005fotherwise_005f2 = _jspx_th_c_005fotherwise_005f2.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("		                                    <li><a href=\"logout.do\">로그아웃</a></li>\n");
          out.write("		                                    <li><a onclick=\"goMypage()\" style=\"cursor:pointer;\">마이페이지</a></li>\n");
          out.write("		                                 ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f2);
      _jspx_th_c_005fotherwise_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f2_reused);
    }
    return false;
  }
}
